// miniprogram/pages/select_flower/select_flower.js
const flowers = [{
    "pinyin": "zhenzhudiaolan",
    "name": "珍珠吊兰"
  }, {
    "pinyin": "yuyemei",
    "name": "榆叶梅"
  }, {
    "pinyin": "hehuan",
    "name": "合欢"
  }, {
    "pinyin": "dahuaziwei",
    "name": "大花紫薇"
  }, {
    "pinyin": "fudicai",
    "name": "附地菜"
  }, {
    "pinyin": "guaiqin",
    "name": "拐芹"
  }, {
    "pinyin": "juanbaofengmaoju",
    "name": "卷苞风毛菊"
  }, {
    "pinyin": "baishu",
    "name": "白术"
  }, {
    "pinyin": "zhuyajingtian",
    "name": "珠芽景天"
  }, {
    "pinyin": "shaoruibaijiang",
    "name": "少蕊败酱"
  }, {
    "pinyin": "caobenweilingxian",
    "name": "草本威灵仙"
  }, {
    "pinyin": "xiangnanxing",
    "name": "象南星"
  }, {
    "pinyin": "dabaojingtian",
    "name": "大苞景天"
  }, {
    "pinyin": "dalangdu",
    "name": "大狼毒"
  }, {
    "pinyin": "daji",
    "name": "大戟"
  }, {
    "pinyin": "youdiancao",
    "name": "油点草"
  }, {
    "pinyin": "shenlanshuweicao",
    "name": "深蓝鼠尾草"
  }, {
    "pinyin": "maogen",
    "name": "毛茛"
  }, {
    "pinyin": "shuzhanglaoguancao",
    "name": "鼠掌老鹳草"
  }, {
    "pinyin": "cuique",
    "name": "翠雀"
  }, {
    "pinyin": "ciqin",
    "name": "刺芹"
  }, {
    "pinyin": "yiyenanyangshan",
    "name": "异叶南洋杉"
  }, {
    "pinyin": "chuimoli",
    "name": "垂茉莉"
  }, {
    "pinyin": "yuejiancao",
    "name": "月见草"
  }, {
    "pinyin": "wuxinghua",
    "name": "五星花"
  }, {
    "pinyin": "fengyanlan",
    "name": "凤眼蓝"
  }, {
    "pinyin": "diaolan",
    "name": "吊兰"
  }, {
    "pinyin": "dayantong",
    "name": "大岩桐"
  }, {
    "pinyin": "cuiju",
    "name": "翠菊"
  }, {
    "pinyin": "jianpuzhailongxueshu",
    "name": "柬埔寨龙血树"
  }, {
    "pinyin": "jingmiancao",
    "name": "镜面草"
  }, {
    "pinyin": "yuanyejiaocao",
    "name": "圆叶椒草"
  }, {
    "pinyin": "lüluo",
    "name": "绿萝"
  }, {
    "pinyin": "fuguizhu",
    "name": "富贵竹"
  }, {
    "pinyin": "jiatanhua",
    "name": "假昙花"
  }, {
    "pinyin": "huweilan",
    "name": "虎尾兰"
  }, {
    "pinyin": "guali",
    "name": "瓜栗"
  }, {
    "pinyin": "ezhangteng",
    "name": "鹅掌藤"
  }, {
    "pinyin": "aimudan",
    "name": "矮牡丹"
  }, {
    "pinyin": "xiangshizhu",
    "name": "香石竹"
  }, {
    "pinyin": "feihuayu",
    "name": "绯花玉"
  }, {
    "pinyin": "hongjiao",
    "name": "红蕉"
  }, {
    "pinyin": "xieweijiao",
    "name": "蝎尾蕉"
  }, {
    "pinyin": "dalihua",
    "name": "大丽花"
  }, {
    "pinyin": "xiaomai",
    "name": "小麦"
  }, {
    "pinyin": "hongbaoxilinyu",
    "name": "红苞喜林芋"
  }, {
    "pinyin": "matilian",
    "name": "马蹄莲"
  }, {
    "pinyin": "xiaoguoshi",
    "name": "小果柿"
  }, {
    "pinyin": "tiezi",
    "name": "铁仔"
  }, {
    "pinyin": "ribennüzhen",
    "name": "日本女贞"
  }, {
    "pinyin": "yangjiegeng",
    "name": "洋桔梗"
  }, {
    "pinyin": "huamaogen",
    "name": "花毛茛"
  }, {
    "pinyin": "xiaohongyi",
    "name": "小红衣"
  }, {
    "pinyin": "sijihaitang",
    "name": "四季海棠"
  }, {
    "pinyin": "xiezhualan",
    "name": "蟹爪兰"
  }, {
    "pinyin": "chuihuaxuanlinghua",
    "name": "垂花悬铃花"
  }, {
    "pinyin": "hongqueshanhu",
    "name": "红雀珊瑚"
  }, {
    "pinyin": "huayewannianqing",
    "name": "花叶万年青"
  }, {
    "pinyin": "baihe",
    "name": "百合"
  }, {
    "pinyin": "buxuecao",
    "name": "补血草"
  }, {
    "pinyin": "longguzhu",
    "name": "龙骨柱"
  }, {
    "pinyin": "tuzhuangxiuxianju",
    "name": "土庄绣线菊"
  }, {
    "pinyin": "guangdongwannianqing",
    "name": "广东万年青"
  }, {
    "pinyin": "zhangruishitouhua",
    "name": "长蕊石头花"
  }, {
    "pinyin": "mei",
    "name": "梅"
  }, {
    "pinyin": "shantao",
    "name": "山桃"
  }, {
    "pinyin": "qilinzhang",
    "name": "麒麟掌"
  }, {
    "pinyin": "hongeqingma",
    "name": "红萼苘麻"
  }, {
    "pinyin": "baihuacaomuxi",
    "name": "白花草木犀"
  }, {
    "pinyin": "baoshihua",
    "name": "宝石花"
  }, {
    "pinyin": "yulu",
    "name": "玉露"
  }, {
    "pinyin": "jiegumu",
    "name": "接骨木"
  }, {
    "pinyin": "pingzhixunzi",
    "name": "平枝栒子"
  }, {
    "pinyin": "jiemaofeilian",
    "name": "节毛飞廉"
  }, {
    "pinyin": "shuitahua",
    "name": "水塔花"
  }, {
    "pinyin": "xuanlingmu",
    "name": "悬铃木"
  }, {
    "pinyin": "hongmaticao",
    "name": "红马蹄草"
  }, {
    "pinyin": "yekui",
    "name": "野葵"
  }, {
    "pinyin": "yuanyejinkui",
    "name": "圆叶锦葵"
  }, {
    "pinyin": "xiabaotuowu",
    "name": "狭苞橐吾"
  }, {
    "pinyin": "xihulu",
    "name": "西葫芦"
  }, {
    "pinyin": "tiangua",
    "name": "甜瓜"
  }, {
    "pinyin": "diaodengshu",
    "name": "吊灯树"
  }, {
    "pinyin": "yuanbo",
    "name": "圆柏"
  }, {
    "pinyin": "shuobaoqiangwei",
    "name": "硕苞蔷薇"
  }, {
    "pinyin": "baiyutang",
    "name": "白玉堂"
  }, {
    "pinyin": "niujincao",
    "name": "牛筋草"
  }, {
    "pinyin": "maidong",
    "name": "麦冬"
  }, {
    "pinyin": "caodizaoshuhe",
    "name": "草地早熟禾"
  }, {
    "pinyin": "zaoshuhe",
    "name": "早熟禾"
  }, {
    "pinyin": "faguowutong",
    "name": "法国梧桐"
  }, {
    "pinyin": "xinjiangyang",
    "name": "新疆杨"
  }, {
    "pinyin": "hongshantao",
    "name": "红山桃"
  }, {
    "pinyin": "liaodongqimu",
    "name": "辽东桤木"
  }, {
    "pinyin": "zhoupimugua",
    "name": "皱皮木瓜"
  }, {
    "pinyin": "yuejihua",
    "name": "月季花"
  }, {
    "pinyin": "fenghuayueji",
    "name": "丰花月季"
  }, {
    "pinyin": "longyahua",
    "name": "龙牙花"
  }, {
    "pinyin": "hucimei",
    "name": "虎刺梅"
  }, {
    "pinyin": "dahuahuilan",
    "name": "大花蕙兰"
  }, {
    "pinyin": "xiankelai",
    "name": "仙客来"
  }, {
    "pinyin": "huzhenzi",
    "name": "虎榛子"
  }, {
    "pinyin": "huangshanyulan",
    "name": "黄山玉兰"
  }, {
    "pinyin": "zhangshouhua",
    "name": "长寿花"
  }, {
    "pinyin": "huangli",
    "name": "黄丽"
  }, {
    "pinyin": "huangmaozhang",
    "name": "黄毛掌"
  }, {
    "pinyin": "banlan",
    "name": "板蓝"
  }, {
    "pinyin": "ke",
    "name": "柯"
  }, {
    "pinyin": "zhongbanyuyemei",
    "name": "重瓣榆叶梅"
  }, {
    "pinyin": "xiangsicao",
    "name": "香丝草"
  }, {
    "pinyin": "cibo",
    "name": "刺柏"
  }, {
    "pinyin": "shezushishan",
    "name": "蛇足石杉"
  }, {
    "pinyin": "shumachixian",
    "name": "树马齿苋"
  }, {
    "pinyin": "luhui",
    "name": "芦荟"
  }, {
    "pinyin": "tiexianjue",
    "name": "铁线蕨"
  }, {
    "pinyin": "yinghongdujuan",
    "name": "迎红杜鹃"
  }, {
    "pinyin": "xiuzhenyezi",
    "name": "袖珍椰子"
  }, {
    "pinyin": "malabali",
    "name": "马拉巴栗"
  }, {
    "pinyin": "gougancai",
    "name": "狗肝菜"
  }, {
    "pinyin": "baiheyu",
    "name": "白鹤芋"
  }, {
    "pinyin": "zhongbanzhujin",
    "name": "重瓣朱槿"
  }, {
    "pinyin": "kulasuoluhui",
    "name": "库拉索芦荟"
  }, {
    "pinyin": "xianglongxueshu",
    "name": "香龙血树"
  }, {
    "pinyin": "eryuyanjue",
    "name": "耳羽岩蕨"
  }, {
    "pinyin": "zhubo",
    "name": "竹柏"
  }, {
    "pinyin": "baichan",
    "name": "白蟾"
  }, {
    "pinyin": "wandailan",
    "name": "万代兰"
  }, {
    "pinyin": "sumu",
    "name": "苏木"
  }, {
    "pinyin": "shihu",
    "name": "石斛"
  }, {
    "pinyin": "zhizhubaodan",
    "name": "蜘蛛抱蛋"
  }, {
    "pinyin": "baihuadujuan",
    "name": "白花杜鹃"
  }, {
    "pinyin": "xianrenqiu",
    "name": "仙人球"
  }, {
    "pinyin": "guipiziji",
    "name": "桂皮紫萁"
  }, {
    "pinyin": "pukui",
    "name": "蒲葵"
  }, {
    "pinyin": "yulongguanyin",
    "name": "玉龙观音"
  }, {
    "pinyin": "chamei",
    "name": "茶梅"
  }, {
    "pinyin": "sutie",
    "name": "苏铁"
  }, {
    "pinyin": "shanzuojiangcao",
    "name": "山酢浆草"
  }, {
    "pinyin": "baisuihua",
    "name": "白穗花"
  }, {
    "pinyin": "xuetieyu",
    "name": "雪铁芋"
  }, {
    "pinyin": "wannianqing",
    "name": "万年青"
  }, {
    "pinyin": "jianyesizhaohua",
    "name": "尖叶四照花"
  }, {
    "pinyin": "huangjing",
    "name": "黄荆"
  }, {
    "pinyin": "katelan",
    "name": "卡特兰"
  }, {
    "pinyin": "hongzhang",
    "name": "红掌"
  }, {
    "pinyin": "jinqianmu",
    "name": "金钱木"
  }, {
    "pinyin": "hongyebitao",
    "name": "红叶碧桃"
  }, {
    "pinyin": "lianqiao",
    "name": "连翘"
  }, {
    "pinyin": "sanqiuxuanlingmu",
    "name": "三球悬铃木"
  }, {
    "pinyin": "haisang",
    "name": "海桑"
  }, {
    "pinyin": "huazhen",
    "name": "华榛"
  }, {
    "pinyin": "zuomu",
    "name": "柞木"
  }, {
    "pinyin": "biandanteng",
    "name": "扁担藤"
  }, {
    "pinyin": "oudingxiang",
    "name": "欧丁香"
  }, {
    "pinyin": "jinzhihuai",
    "name": "金枝槐"
  }, {
    "pinyin": "xing",
    "name": "杏"
  }, {
    "pinyin": "zhongbanfenhonghaitanghua",
    "name": "重瓣粉红海棠花"
  }, {
    "pinyin": "yulan",
    "name": "玉兰"
  }, {
    "pinyin": "xianjuxing",
    "name": "仙居杏"
  }, {
    "pinyin": "duanyeshuiwugong",
    "name": "短叶水蜈蚣"
  }, {
    "pinyin": "huaishu",
    "name": "槐树"
  }, {
    "pinyin": "langyu",
    "name": "榔榆"
  }, {
    "pinyin": "shamomeigui",
    "name": "沙漠玫瑰"
  }, {
    "pinyin": "longzhuasang",
    "name": "龙爪桑"
  }, {
    "pinyin": "shuixunzi",
    "name": "水栒子"
  }, {
    "pinyin": "ribenmugua",
    "name": "日本木瓜"
  }, {
    "pinyin": "dongqingweimao",
    "name": "冬青卫矛"
  }, {
    "pinyin": "babaojingtian",
    "name": "八宝景天"
  }, {
    "pinyin": "maili",
    "name": "麦李"
  }, {
    "pinyin": "baohuayulan",
    "name": "宝华玉兰"
  }, {
    "pinyin": "zaokaijincai",
    "name": "早开堇菜"
  }, {
    "pinyin": "ribenwanying",
    "name": "日本晚樱"
  }, {
    "pinyin": "shanmagan",
    "name": "山麻杆"
  }, {
    "pinyin": "longbo",
    "name": "龙柏"
  }, {
    "pinyin": "dayezaoying",
    "name": "大叶早樱"
  }, {
    "pinyin": "zhangyehuangzhongmu",
    "name": "掌叶黄钟木"
  }, {
    "pinyin": "maoyeshantongzi",
    "name": "毛叶山桐子"
  }, {
    "pinyin": "kuanyetaicao",
    "name": "宽叶薹草"
  }, {
    "pinyin": "zhouyegouweicao",
    "name": "皱叶狗尾草"
  }, {
    "pinyin": "yanhua",
    "name": "芫花"
  }, {
    "pinyin": "zidingxiang",
    "name": "紫丁香"
  }, {
    "pinyin": "hongdingxiang",
    "name": "红丁香"
  }, {
    "pinyin": "mengguxinba",
    "name": "蒙古芯芭"
  }, {
    "pinyin": "tangchangpu",
    "name": "唐菖蒲"
  }, {
    "pinyin": "hongfengcai",
    "name": "红凤菜"
  }, {
    "pinyin": "qiuzili",
    "name": "秋子梨"
  }, {
    "pinyin": "gouxiandaji",
    "name": "钩腺大戟"
  }, {
    "pinyin": "baichezhoucao",
    "name": "白车轴草"
  }, {
    "pinyin": "suan",
    "name": "蒜"
  }, {
    "pinyin": "gangzhu",
    "name": "刚竹"
  }, {
    "pinyin": "jiang",
    "name": "姜"
  }, {
    "pinyin": "wengcai",
    "name": "蕹菜"
  }, {
    "pinyin": "shanxing",
    "name": "山杏"
  }, {
    "pinyin": "nüzhen",
    "name": "女贞"
  }, {
    "pinyin": "yingchunhua",
    "name": "迎春花"
  }, {
    "pinyin": "xifuhaitang",
    "name": "西府海棠"
  }, {
    "pinyin": "yuli",
    "name": "郁李"
  }, {
    "pinyin": "tao",
    "name": "桃"
  }, {
    "pinyin": "ziyeaiying",
    "name": "紫叶矮樱"
  }, {
    "pinyin": "ziyeli",
    "name": "紫叶李"
  }, {
    "pinyin": "bitao",
    "name": "碧桃"
  }, {
    "pinyin": "jianliejiahaiyangcan",
    "name": "尖裂假还阳参"
  }, {
    "pinyin": "dongjingyinghua",
    "name": "东京樱花"
  }, {
    "pinyin": "shali",
    "name": "沙梨"
  }, {
    "pinyin": "douli",
    "name": "豆梨"
  }, {
    "pinyin": "baili",
    "name": "白梨"
  }, {
    "pinyin": "qiulan",
    "name": "球兰"
  }, {
    "pinyin": "zhonghuakumaicai",
    "name": "中华苦荬菜"
  }, {
    "pinyin": "dongbeipugongying",
    "name": "东北蒲公英"
  }, {
    "pinyin": "ribenxiaobo",
    "name": "日本小檗"
  }, {
    "pinyin": "meigui",
    "name": "玫瑰"
  }, {
    "pinyin": "junzilan",
    "name": "君子兰"
  }, {
    "pinyin": "yuzan",
    "name": "玉簪"
  }, {
    "pinyin": "baizicai",
    "name": "白子菜"
  }, {
    "pinyin": "qudielian",
    "name": "趣蝶莲"
  }, {
    "pinyin": "pingwojusanqi",
    "name": "平卧菊三七"
  }, {
    "pinyin": "caoyeshu",
    "name": "糙叶树"
  }, {
    "pinyin": "jiayang",
    "name": "加杨"
  }, {
    "pinyin": "zhongjieshihu",
    "name": "肿节石斛"
  }, {
    "pinyin": "qiuhaitang",
    "name": "秋海棠"
  }, {
    "pinyin": "ziyetaohua",
    "name": "紫叶桃花"
  }, {
    "pinyin": "cangshu",
    "name": "苍术"
  }, {
    "pinyin": "juanmaopufuweilingcai",
    "name": "绢毛匍匐委陵菜"
  }, {
    "pinyin": "zihuafengli",
    "name": "紫花凤梨"
  }, {
    "pinyin": "heli",
    "name": "褐梨"
  }, {
    "pinyin": "kutiaofeng",
    "name": "苦条枫"
  }, {
    "pinyin": "zhugecai",
    "name": "诸葛菜"
  }, {
    "pinyin": "danhuayuanwei",
    "name": "单花鸢尾"
  }, {
    "pinyin": "biandangan",
    "name": "扁担杆"
  }, {
    "pinyin": "ziyuzan",
    "name": "紫玉簪"
  }, {
    "pinyin": "juhuatao",
    "name": "菊花桃"
  }, {
    "pinyin": "feitao",
    "name": "绯桃"
  }, {
    "pinyin": "guangdongsheputao",
    "name": "广东蛇葡萄"
  }, {
    "pinyin": "nanzhu",
    "name": "南烛"
  }, {
    "pinyin": "wuyedijin",
    "name": "五叶地锦"
  }, {
    "pinyin": "pingcheqian",
    "name": "平车前"
  }, {
    "pinyin": "babao",
    "name": "八宝"
  }, {
    "pinyin": "furongju",
    "name": "芙蓉菊"
  }, {
    "pinyin": "zhangyaobabao",
    "name": "长药八宝"
  }, {
    "pinyin": "guiyingsu",
    "name": "鬼罂粟"
  }, {
    "pinyin": "zhangejincai",
    "name": "长萼堇菜"
  }, {
    "pinyin": "huaxirendong",
    "name": "华西忍冬"
  }, {
    "pinyin": "jinhuarendong",
    "name": "金花忍冬"
  }, {
    "pinyin": "zijing",
    "name": "紫荆"
  }, {
    "pinyin": "shanxiaoju",
    "name": "山小橘"
  }, {
    "pinyin": "liuzhiweimao",
    "name": "瘤枝卫矛"
  }, {
    "pinyin": "rendong",
    "name": "忍冬"
  }, {
    "pinyin": "shanshiliu",
    "name": "山石榴"
  }, {
    "pinyin": "maogouteng",
    "name": "毛钩藤"
  }, {
    "pinyin": "jinsitao",
    "name": "金丝桃"
  }, {
    "pinyin": "xiayihua",
    "name": "虾衣花"
  }, {
    "pinyin": "zhongbanmaili",
    "name": "重瓣麦李"
  }, {
    "pinyin": "shanjingzi",
    "name": "山荆子"
  }, {
    "pinyin": "pingguo",
    "name": "苹果"
  }, {
    "pinyin": "zhusimaolanercao",
    "name": "蛛丝毛蓝耳草"
  }, {
    "pinyin": "zaohuarendong",
    "name": "早花忍冬"
  }, {
    "pinyin": "congpirendong",
    "name": "葱皮忍冬"
  }, {
    "pinyin": "zhenzhumei",
    "name": "珍珠梅"
  }, {
    "pinyin": "baihua",
    "name": "白桦"
  }, {
    "pinyin": "xuesong",
    "name": "雪松"
  }, {
    "pinyin": "xiaoguoqiangwei",
    "name": "小果蔷薇"
  }, {
    "pinyin": "nanmuxu",
    "name": "南苜蓿"
  }, {
    "pinyin": "longzhualiu",
    "name": "龙爪柳"
  }, {
    "pinyin": "nihuamucao",
    "name": "泥花母草"
  }, {
    "pinyin": "feiyangcao",
    "name": "飞扬草"
  }, {
    "pinyin": "rouruobanzhongcao",
    "name": "柔弱斑种草"
  }, {
    "pinyin": "luobu",
    "name": "萝卜"
  }, {
    "pinyin": "yidianhong",
    "name": "一点红"
  }, {
    "pinyin": "duzhong",
    "name": "杜仲"
  }, {
    "pinyin": "banxia",
    "name": "半夏"
  }, {
    "pinyin": "maoshanzha",
    "name": "毛山楂"
  }, {
    "pinyin": "yushu",
    "name": "榆树"
  }, {
    "pinyin": "sang",
    "name": "桑"
  }, {
    "pinyin": "longzhuazao",
    "name": "龙爪枣"
  }, {
    "pinyin": "fengdan",
    "name": "凤丹"
  }, {
    "pinyin": "longyacao",
    "name": "龙芽草"
  }, {
    "pinyin": "yingsu",
    "name": "罂粟"
  }, {
    "pinyin": "dunyetianzhukui",
    "name": "盾叶天竺葵"
  }, {
    "pinyin": "pengpengxiang",
    "name": "碰碰香"
  }, {
    "pinyin": "jiatianzhukui",
    "name": "家天竺葵"
  }, {
    "pinyin": "machixian",
    "name": "马齿苋"
  }, {
    "pinyin": "liaozicao",
    "name": "蓼子草"
  }, {
    "pinyin": "xunyicao",
    "name": "薰衣草"
  }, {
    "pinyin": "yinliu",
    "name": "银柳"
  }, {
    "pinyin": "daguoyu",
    "name": "大果榆"
  }, {
    "pinyin": "tangsongcao",
    "name": "唐松草"
  }, {
    "pinyin": "heihua",
    "name": "黑桦"
  }, {
    "pinyin": "sanliexiuxianju",
    "name": "三裂绣线菊"
  }, {
    "pinyin": "hongruimu",
    "name": "红瑞木"
  }, {
    "pinyin": "jiangnanqimu",
    "name": "江南桤木"
  }, {
    "pinyin": "baoli",
    "name": "枹栎"
  }, {
    "pinyin": "qingyang",
    "name": "青杨"
  }, {
    "pinyin": "dazimihoutao",
    "name": "大籽猕猴桃"
  }, {
    "pinyin": "ribenqimu",
    "name": "日本桤木"
  }, {
    "pinyin": "maoshanjingzi",
    "name": "毛山荆子"
  }, {
    "pinyin": "xinyehuanghuaren",
    "name": "心叶黄花稔"
  }, {
    "pinyin": "xingyeshacan",
    "name": "杏叶沙参"
  }, {
    "pinyin": "dongbeichabiaozi",
    "name": "东北茶藨子"
  }, {
    "pinyin": "hongfeng",
    "name": "红枫"
  }, {
    "pinyin": "yeqiangwei",
    "name": "野蔷薇"
  }, {
    "pinyin": "cican",
    "name": "刺参"
  }, {
    "pinyin": "wugencao",
    "name": "屋根草"
  }, {
    "pinyin": "dongbeiyuzan",
    "name": "东北玉簪"
  }, {
    "pinyin": "zhonghuajinyeyu",
    "name": "中华金叶榆"
  }, {
    "pinyin": "liusushu",
    "name": "流苏树"
  }, {
    "pinyin": "honghuabitao",
    "name": "红花碧桃"
  }, {
    "pinyin": "fentuanqiangwei",
    "name": "粉团蔷薇"
  }, {
    "pinyin": "chaojue",
    "name": "巢蕨"
  }, {
    "pinyin": "shemei",
    "name": "蛇莓"
  }, {
    "pinyin": "zhejiangshancha",
    "name": "浙江山茶"
  }, {
    "pinyin": "chuisihaitang",
    "name": "垂丝海棠"
  }, {
    "pinyin": "xianrenzhi",
    "name": "仙人指"
  }, {
    "pinyin": "zhongbanditanghua",
    "name": "重瓣棣棠花"
  }, {
    "pinyin": "feizhouju",
    "name": "非洲菊"
  }, {
    "pinyin": "hewanglan",
    "name": "鹤望兰"
  }, {
    "pinyin": "laju",
    "name": "蜡菊"
  }, {
    "pinyin": "shexiangbaihe",
    "name": "麝香百合"
  }, {
    "pinyin": "gaopenyingtao",
    "name": "高盆樱桃"
  }, {
    "pinyin": "huimaohuanglu",
    "name": "灰毛黄栌"
  }, {
    "pinyin": "taiwanlinqin",
    "name": "台湾林檎"
  }, {
    "pinyin": "huangcimei",
    "name": "黄刺玫"
  }, {
    "pinyin": "taiwanpaotong",
    "name": "台湾泡桐"
  }, {
    "pinyin": "jinzhonghua",
    "name": "金钟花"
  }, {
    "pinyin": "taipinghua",
    "name": "太平花"
  }, {
    "pinyin": "jushu",
    "name": "榉树"
  }, {
    "pinyin": "longzhuayu",
    "name": "龙爪榆"
  }, {
    "pinyin": "shuci",
    "name": "鼠刺"
  }, {
    "pinyin": "huabeizhenzhumei",
    "name": "华北珍珠梅"
  }, {
    "pinyin": "huajiao",
    "name": "花椒"
  }, {
    "pinyin": "tengtan",
    "name": "藤檀"
  }, {
    "pinyin": "queershetou",
    "name": "雀儿舌头"
  }, {
    "pinyin": "danbanhuangcimei",
    "name": "单瓣黄刺玫"
  }, {
    "pinyin": "jinyenüzhen",
    "name": "金叶女贞"
  }, {
    "pinyin": "shuangsuiquebai",
    "name": "双穗雀稗"
  }, {
    "pinyin": "mumahuang",
    "name": "木麻黄"
  }, {
    "pinyin": "ziyexiaobo",
    "name": "紫叶小檗"
  }, {
    "pinyin": "huangbo",
    "name": "黄檗"
  }, {
    "pinyin": "duli",
    "name": "杜梨"
  }, {
    "pinyin": "daguoyoumateng",
    "name": "大果油麻藤"
  }, {
    "pinyin": "hongsong",
    "name": "红松"
  }, {
    "pinyin": "lankaopaotong",
    "name": "兰考泡桐"
  }, {
    "pinyin": "ziteng",
    "name": "紫藤"
  }, {
    "pinyin": "qiuzi",
    "name": "楸子"
  }, {
    "pinyin": "yujinxiang",
    "name": "郁金香"
  }, {
    "pinyin": "huahong",
    "name": "花红"
  }, {
    "pinyin": "xiuqiujiami",
    "name": "绣球荚蒾"
  }, {
    "pinyin": "kumaicai",
    "name": "苦荬菜"
  }, {
    "pinyin": "jimaosong",
    "name": "鸡毛松"
  }, {
    "pinyin": "dianqianhuangtan",
    "name": "滇黔黄檀"
  }, {
    "pinyin": "li",
    "name": "李"
  }, {
    "pinyin": "xiangyuan",
    "name": "香橼"
  }, {
    "pinyin": "xiangyetianzhukui",
    "name": "香叶天竺葵"
  }, {
    "pinyin": "kucan",
    "name": "苦参"
  }, {
    "pinyin": "chuju",
    "name": "雏菊"
  }, {
    "pinyin": "ejuhua",
    "name": "萼距花"
  }, {
    "pinyin": "zibanmudan",
    "name": "紫斑牡丹"
  }, {
    "pinyin": "changchunyoumateng",
    "name": "常春油麻藤"
  }, {
    "pinyin": "maopaotong",
    "name": "毛泡桐"
  }, {
    "pinyin": "yanghuai",
    "name": "洋槐"
  }, {
    "pinyin": "damai",
    "name": "大麦"
  }, {
    "pinyin": "molihua",
    "name": "茉莉花"
  }, {
    "pinyin": "kutangguo",
    "name": "苦糖果"
  }, {
    "pinyin": "huoji",
    "name": "火祭"
  }, {
    "pinyin": "liulanxiang",
    "name": "留兰香"
  }, {
    "pinyin": "guibeizhu",
    "name": "龟背竹"
  }, {
    "pinyin": "tiehaitang",
    "name": "铁海棠"
  }, {
    "pinyin": "foshouzhang",
    "name": "佛手掌"
  }, {
    "pinyin": "zizhumei",
    "name": "紫竹梅"
  }, {
    "pinyin": "yanzhizhang",
    "name": "胭脂掌"
  }, {
    "pinyin": "shanzaojia",
    "name": "山皂荚"
  }, {
    "pinyin": "putao",
    "name": "葡萄"
  }, {
    "pinyin": "baihuazilucao",
    "name": "白花紫露草"
  }, {
    "pinyin": "zhujin",
    "name": "朱槿"
  }, {
    "pinyin": "meiguozaojia",
    "name": "美国皂荚"
  }, {
    "pinyin": "hutao",
    "name": "胡桃"
  }, {
    "pinyin": "diaodengfusang",
    "name": "吊灯芙桑"
  }, {
    "pinyin": "niunaizi",
    "name": "牛奶子"
  }, {
    "pinyin": "honghuajinjier",
    "name": "红花锦鸡儿"
  }, {
    "pinyin": "menggupugongying",
    "name": "蒙古蒲公英"
  }, {
    "pinyin": "yezihua",
    "name": "叶子花"
  }, {
    "pinyin": "dayepo",
    "name": "大叶朴"
  }, {
    "pinyin": "ciyu",
    "name": "刺榆"
  }, {
    "pinyin": "fanshiliu",
    "name": "番石榴"
  }, {
    "pinyin": "zhudinghong",
    "name": "朱顶红"
  }, {
    "pinyin": "lingjianhehua",
    "name": "令箭荷花"
  }, {
    "pinyin": "hudielan",
    "name": "蝴蝶兰"
  }, {
    "pinyin": "shaoyao",
    "name": "芍药"
  }, {
    "pinyin": "yinggulingxiao",
    "name": "硬骨凌霄"
  }, {
    "pinyin": "meiqiangwei",
    "name": "美蔷薇"
  }, {
    "pinyin": "pinglanhua",
    "name": "瓶兰花"
  }, {
    "pinyin": "wuyaguo",
    "name": "五桠果"
  }, {
    "pinyin": "qianbanbaitao",
    "name": "千瓣白桃"
  }, {
    "pinyin": "jianma",
    "name": "剑麻"
  }, {
    "pinyin": "huangshansong",
    "name": "黄山松"
  }, {
    "pinyin": "huananwuzhensong",
    "name": "华南五针松"
  }, {
    "pinyin": "huangsanfeng",
    "name": "幌伞枫"
  }, {
    "pinyin": "xianggenyuanwei",
    "name": "香根鸢尾"
  }, {
    "pinyin": "fanshu",
    "name": "番薯"
  }, {
    "pinyin": "jinyinrendong",
    "name": "金银忍冬"
  }, {
    "pinyin": "weishi",
    "name": "蝟实"
  }, {
    "pinyin": "xingandujuan",
    "name": "兴安杜鹃"
  }, {
    "pinyin": "shanlihong",
    "name": "山里红"
  }, {
    "pinyin": "yunnanqiyeshu",
    "name": "云南七叶树"
  }, {
    "pinyin": "xiboliyayuanwei",
    "name": "西伯利亚鸢尾"
  }, {
    "pinyin": "qianniu",
    "name": "牵牛"
  }, {
    "pinyin": "gongtong",
    "name": "珙桐"
  }, {
    "pinyin": "xiaoyebaixinshu",
    "name": "小叶白辛树"
  }, {
    "pinyin": "houqiaoshu",
    "name": "厚壳树"
  }, {
    "pinyin": "fangli",
    "name": "仿栗"
  }, {
    "pinyin": "yemoli",
    "name": "野茉莉"
  }, {
    "pinyin": "sanhuafeng",
    "name": "三花枫"
  }, {
    "pinyin": "jindaihua",
    "name": "锦带花"
  }, {
    "pinyin": "zhouyesuanmo",
    "name": "皱叶酸模"
  }, {
    "pinyin": "yunshan",
    "name": "云杉"
  }, {
    "pinyin": "hongpiyunshan",
    "name": "红皮云杉"
  }, {
    "pinyin": "meizhouhongcen",
    "name": "美洲红梣"
  }, {
    "pinyin": "yuanwei",
    "name": "鸢尾"
  }, {
    "pinyin": "malin",
    "name": "马蔺"
  }, {
    "pinyin": "hanliu",
    "name": "旱柳"
  }, {
    "pinyin": "hongchezhoucao",
    "name": "红车轴草"
  }, {
    "pinyin": "pudibo",
    "name": "铺地柏"
  }, {
    "pinyin": "mujin",
    "name": "木槿"
  }, {
    "pinyin": "huanglu",
    "name": "黄栌"
  }, {
    "pinyin": "qizimei",
    "name": "七姊妹"
  }, {
    "pinyin": "maoyanghuai",
    "name": "毛洋槐"
  }, {
    "pinyin": "yancao",
    "name": "烟草"
  }, {
    "pinyin": "jinjier",
    "name": "锦鸡儿"
  }, {
    "pinyin": "meinüying",
    "name": "美女樱"
  }, {
    "pinyin": "lujiaogui",
    "name": "鹿角桧"
  }, {
    "pinyin": "chaziyuanbo",
    "name": "叉子圆柏"
  }, {
    "pinyin": "xianbo",
    "name": "线柏"
  }, {
    "pinyin": "fengweisilan",
    "name": "凤尾丝兰"
  }, {
    "pinyin": "zhangbingshuanghuamu",
    "name": "长柄双花木"
  }, {
    "pinyin": "haitanghua",
    "name": "海棠花"
  }, {
    "pinyin": "bichisutie",
    "name": "篦齿苏铁"
  }, {
    "pinyin": "yuchanhua",
    "name": "玉蝉花"
  }, {
    "pinyin": "lieyeyu",
    "name": "裂叶榆"
  }, {
    "pinyin": "songlan",
    "name": "菘蓝"
  }, {
    "pinyin": "zaojiashu",
    "name": "皂荚树"
  }, {
    "pinyin": "jinbianhuweilan",
    "name": "金边虎尾兰"
  }, {
    "pinyin": "chihua",
    "name": "黐花"
  }, {
    "pinyin": "mubenmantuoluo",
    "name": "木本曼陀罗"
  }, {
    "pinyin": "huimaodaqing",
    "name": "灰毛大青"
  }, {
    "pinyin": "tianjing",
    "name": "田菁"
  }, {
    "pinyin": "huanglianmu",
    "name": "黄连木"
  }, {
    "pinyin": "nihucai",
    "name": "泥胡菜"
  }, {
    "pinyin": "wangcao",
    "name": "菵草"
  }, {
    "pinyin": "wuxincai",
    "name": "无心菜"
  }, {
    "pinyin": "baidingzaoshuhe",
    "name": "白顶早熟禾"
  }, {
    "pinyin": "li",
    "name": "藜"
  }, {
    "pinyin": "kujucai",
    "name": "苦苣菜"
  }, {
    "pinyin": "duxingcai",
    "name": "独行菜"
  }, {
    "pinyin": "xiaohuatangjie",
    "name": "小花糖芥"
  }, {
    "pinyin": "jiantouyeli",
    "name": "尖头叶藜"
  }, {
    "pinyin": "chaotianweilingcai",
    "name": "朝天委陵菜"
  }, {
    "pinyin": "baishantao",
    "name": "白山桃"
  }, {
    "pinyin": "guijiadongqing",
    "name": "龟甲冬青"
  }, {
    "pinyin": "tianhusui",
    "name": "天胡荽"
  }, {
    "pinyin": "shizhu",
    "name": "石竹"
  }, {
    "pinyin": "maosuililu",
    "name": "毛穗藜芦"
  }, {
    "pinyin": "dunyetangsongcao",
    "name": "盾叶唐松草"
  }, {
    "pinyin": "jinglanbiancao",
    "name": "井栏边草"
  }, {
    "pinyin": "hualingcao",
    "name": "花菱草"
  }, {
    "pinyin": "jinzhiguohuai",
    "name": "金枝国槐"
  }, {
    "pinyin": "songxialan",
    "name": "松下兰"
  }, {
    "pinyin": "zhangmuwanglian",
    "name": "长木王莲"
  }, {
    "pinyin": "yumeiren",
    "name": "虞美人"
  }, {
    "pinyin": "ouzhoutianyingtao",
    "name": "欧洲甜樱桃"
  }, {
    "pinyin": "mutongmadouling",
    "name": "木通马兜铃"
  }, {
    "pinyin": "laohuci",
    "name": "老虎刺"
  }, {
    "pinyin": "hudixiao",
    "name": "忽地笑"
  }, {
    "pinyin": "yangputao",
    "name": "洋蒲桃"
  }, {
    "pinyin": "xinyerizhonghua",
    "name": "心叶日中花"
  }, {
    "pinyin": "ciercai",
    "name": "刺儿菜"
  }, {
    "pinyin": "haihongdou",
    "name": "海红豆"
  }, {
    "pinyin": "lamu",
    "name": "辣木"
  }, {
    "pinyin": "ruixiang",
    "name": "瑞香"
  }, {
    "pinyin": "baishuilian",
    "name": "白睡莲"
  }, {
    "pinyin": "yedadou",
    "name": "野大豆"
  }, {
    "pinyin": "jiadidou",
    "name": "假地豆"
  }, {
    "pinyin": "changpu",
    "name": "菖蒲"
  }, {
    "pinyin": "dihuang",
    "name": "地黄"
  }, {
    "pinyin": "zhangbairendong",
    "name": "长白忍冬"
  }, {
    "pinyin": "ouling",
    "name": "欧菱"
  }, {
    "pinyin": "xueliu",
    "name": "雪柳"
  }, {
    "pinyin": "qiu",
    "name": "楸"
  }, {
    "pinyin": "fengxiangguo",
    "name": "风箱果"
  }, {
    "pinyin": "shengguyou",
    "name": "省沽油"
  }, {
    "pinyin": "liaodongdingxiang",
    "name": "辽东丁香"
  }, {
    "pinyin": "ziduan",
    "name": "紫椴"
  }, {
    "pinyin": "jiashimujiangzi",
    "name": "假柿木姜子"
  }, {
    "pinyin": "shanyang",
    "name": "山杨"
  }, {
    "pinyin": "youmu",
    "name": "柚木"
  }, {
    "pinyin": "shanhujiao",
    "name": "山胡椒"
  }, {
    "pinyin": "boyeshuli",
    "name": "薄叶鼠李"
  }, {
    "pinyin": "shujinjier",
    "name": "树锦鸡儿"
  }, {
    "pinyin": "yichuanhong",
    "name": "一串红"
  }, {
    "pinyin": "wanshouju",
    "name": "万寿菊"
  }, {
    "pinyin": "bidongqie",
    "name": "碧冬茄"
  }, {
    "pinyin": "dishaogua",
    "name": "地梢瓜"
  }, {
    "pinyin": "huanghuacai",
    "name": "黄花菜"
  }, {
    "pinyin": "chaoxianhuai",
    "name": "朝鲜槐"
  }, {
    "pinyin": "mihuadou",
    "name": "密花豆"
  }, {
    "pinyin": "maoyemaoweimu",
    "name": "毛叶猫尾木"
  }, {
    "pinyin": "houzhang",
    "name": "猴樟"
  }, {
    "pinyin": "putishu",
    "name": "菩提树"
  }, {
    "pinyin": "shansong",
    "name": "杉松"
  }, {
    "pinyin": "jiaotou",
    "name": "藠头"
  }, {
    "pinyin": "tuanhua",
    "name": "团花"
  }, {
    "pinyin": "shanbaishu",
    "name": "山白树"
  }, {
    "pinyin": "huoyanshu",
    "name": "火焰树"
  }, {
    "pinyin": "zhonghuaying",
    "name": "钟花樱"
  }, {
    "pinyin": "huli",
    "name": "槲栎"
  }, {
    "pinyin": "heidanshu",
    "name": "黑弹树"
  }, {
    "pinyin": "xiangyeyang",
    "name": "响叶杨"
  }, {
    "pinyin": "luanyeshuli",
    "name": "卵叶鼠李"
  }, {
    "pinyin": "hebeiyang",
    "name": "河北杨"
  }, {
    "pinyin": "lachangshu",
    "name": "腊肠树"
  }, {
    "pinyin": "hangzhouyu",
    "name": "杭州榆"
  }, {
    "pinyin": "honghuayanghuai",
    "name": "红花洋槐"
  }, {
    "pinyin": "huaquliu",
    "name": "花曲柳"
  }, {
    "pinyin": "mutonghao",
    "name": "木茼蒿"
  }, {
    "pinyin": "ezhangchai",
    "name": "鹅掌柴"
  }, {
    "pinyin": "maobaihe",
    "name": "毛百合"
  }, {
    "pinyin": "zhangliekujucai",
    "name": "长裂苦苣菜"
  }, {
    "pinyin": "shuiquliu",
    "name": "水曲柳"
  }, {
    "pinyin": "bailashu",
    "name": "白蜡树"
  }, {
    "pinyin": "feizhoulian",
    "name": "非洲楝"
  }, {
    "pinyin": "wuyuecha",
    "name": "五月茶"
  }, {
    "pinyin": "xiaoyeyang",
    "name": "小叶杨"
  }, {
    "pinyin": "xiangrikui",
    "name": "向日葵"
  }, {
    "pinyin": "jiangxiang",
    "name": "降香"
  }, {
    "pinyin": "shougongmu",
    "name": "守宫木"
  }, {
    "pinyin": "zitan",
    "name": "紫檀"
  }, {
    "pinyin": "hongchun",
    "name": "红椿"
  }, {
    "pinyin": "maoyelan",
    "name": "毛叶榄"
  }, {
    "pinyin": "jianxuefenghou",
    "name": "见血封喉"
  }, {
    "pinyin": "yangti",
    "name": "羊蹄"
  }, {
    "pinyin": "matang",
    "name": "马唐"
  }, {
    "pinyin": "chenghuangyufenghua",
    "name": "橙黄玉凤花"
  }, {
    "pinyin": "guangyexicigougu",
    "name": "光叶细刺枸骨"
  }, {
    "pinyin": "yeshu",
    "name": "野黍"
  }, {
    "pinyin": "wanggua",
    "name": "王瓜"
  }, {
    "pinyin": "baibabao",
    "name": "白八宝"
  }, {
    "pinyin": "tabo",
    "name": "塔柏"
  }, {
    "pinyin": "bomu",
    "name": "柏木"
  }, {
    "pinyin": "dabaoxuancao",
    "name": "大苞萱草"
  }, {
    "pinyin": "lanhuashuweicao",
    "name": "蓝花鼠尾草"
  }, {
    "pinyin": "xiyemeinüying",
    "name": "细叶美女樱"
  }, {
    "pinyin": "lanmuju",
    "name": "蓝目菊"
  }, {
    "pinyin": "silan",
    "name": "丝兰"
  }, {
    "pinyin": "malian",
    "name": "麻楝"
  }, {
    "pinyin": "wumo",
    "name": "乌墨"
  }, {
    "pinyin": "xiaoputao",
    "name": "肖蒲桃"
  }, {
    "pinyin": "muxi",
    "name": "木犀"
  }, {
    "pinyin": "jiabaoguo",
    "name": "嘉宝果"
  }, {
    "pinyin": "helanju",
    "name": "荷兰菊"
  }, {
    "pinyin": "qiuying",
    "name": "秋英"
  }, {
    "pinyin": "mudan",
    "name": "牡丹"
  }, {
    "pinyin": "longxuhaitang",
    "name": "龙须海棠"
  }, {
    "pinyin": "beihuanghuacai",
    "name": "北黄花菜"
  }, {
    "pinyin": "zhen",
    "name": "榛"
  }, {
    "pinyin": "tianlanmuxu",
    "name": "天蓝苜蓿"
  }, {
    "pinyin": "yiyedijin",
    "name": "异叶地锦"
  }, {
    "pinyin": "zhouguoshemei",
    "name": "皱果蛇莓"
  }, {
    "pinyin": "ruanzaomihoutao",
    "name": "软枣猕猴桃"
  }, {
    "pinyin": "sanyaku",
    "name": "三桠苦"
  }, {
    "pinyin": "shuituanhua",
    "name": "水团花"
  }, {
    "pinyin": "zhanmu",
    "name": "粘木"
  }, {
    "pinyin": "shizixingjin",
    "name": "十字星锦"
  }, {
    "pinyin": "zibao",
    "name": "子宝"
  }, {
    "pinyin": "liulidian",
    "name": "琉璃殿"
  }, {
    "pinyin": "hongzhiyujin",
    "name": "虹之玉锦"
  }, {
    "pinyin": "shilian",
    "name": "石莲"
  }, {
    "pinyin": "xiaoyelengshuihua",
    "name": "小叶冷水花"
  }, {
    "pinyin": "shilianhua",
    "name": "石莲花"
  }, {
    "pinyin": "chiguicheng",
    "name": "赤鬼城"
  }, {
    "pinyin": "meiguiqie",
    "name": "玫瑰茄"
  }, {
    "pinyin": "jumaicai",
    "name": "苣荬菜"
  }, {
    "pinyin": "xiuqiu",
    "name": "绣球"
  }, {
    "pinyin": "ximing",
    "name": "菥蓂"
  }, {
    "pinyin": "gaocuiquehua",
    "name": "高翠雀花"
  }, {
    "pinyin": "linyinshuweicao",
    "name": "林荫鼠尾草"
  }, {
    "pinyin": "mufurong",
    "name": "木芙蓉"
  }, {
    "pinyin": "aotouxian",
    "name": "凹头苋"
  }, {
    "pinyin": "dawanhua",
    "name": "打碗花"
  }, {
    "pinyin": "sansejin",
    "name": "三色堇"
  }, {
    "pinyin": "baiqucai",
    "name": "白屈菜"
  }, {
    "pinyin": "zhuanzilian",
    "name": "转子莲"
  }, {
    "pinyin": "pianxu",
    "name": "萹蓄"
  }, {
    "pinyin": "cebo",
    "name": "侧柏"
  }, {
    "pinyin": "xiyangjiegumu",
    "name": "西洋接骨木"
  }, {
    "pinyin": "huangchangpu",
    "name": "黄菖蒲"
  }, {
    "pinyin": "jinzhanju",
    "name": "金盏菊"
  }, {
    "pinyin": "moluogeliuchuanyu",
    "name": "摩洛哥柳穿鱼"
  }, {
    "pinyin": "jiejiecai",
    "name": "节节菜"
  }, {
    "pinyin": "ciyeguiying",
    "name": "刺叶桂樱"
  }, {
    "pinyin": "chatiaofeng",
    "name": "茶条枫"
  }, {
    "pinyin": "fenhualingxiao",
    "name": "粉花凌霄"
  }, {
    "pinyin": "wenguanguo",
    "name": "文冠果"
  }, {
    "pinyin": "yexiazhu",
    "name": "叶下珠"
  }, {
    "pinyin": "zuojiangcao",
    "name": "酢浆草"
  }, {
    "pinyin": "chouchun",
    "name": "臭椿"
  }, {
    "pinyin": "yeyingsu",
    "name": "野罂粟"
  }, {
    "pinyin": "huijiayunshi",
    "name": "喙荚云实"
  }, {
    "pinyin": "zhuyehuweilan",
    "name": "柱叶虎尾兰"
  }, {
    "pinyin": "xianrenzhu",
    "name": "仙人柱"
  }, {
    "pinyin": "hailanci",
    "name": "海榄雌"
  }, {
    "pinyin": "yangcong",
    "name": "洋葱"
  }, {
    "pinyin": "shehanweilingcai",
    "name": "蛇含委陵菜"
  }, {
    "pinyin": "biandoucai",
    "name": "变豆菜"
  }, {
    "pinyin": "fengxiangshu",
    "name": "枫香树"
  }, {
    "pinyin": "soushu",
    "name": "溲疏"
  }, {
    "pinyin": "shidisong",
    "name": "湿地松"
  }, {
    "pinyin": "baihuayangzijing",
    "name": "白花洋紫荆"
  }, {
    "pinyin": "ruolü",
    "name": "若绿"
  }, {
    "pinyin": "wuhuaguo",
    "name": "无花果"
  }, {
    "pinyin": "daoguajinzhong",
    "name": "倒挂金钟"
  }, {
    "pinyin": "shi",
    "name": "蓍"
  }, {
    "pinyin": "difu",
    "name": "地肤"
  }, {
    "pinyin": "xiaopengcao",
    "name": "小蓬草"
  }, {
    "pinyin": "zuanyeziyu",
    "name": "钻叶紫菀"
  }, {
    "pinyin": "lanhuateng",
    "name": "蓝花藤"
  }, {
    "pinyin": "huoyanlan",
    "name": "火焰兰"
  }, {
    "pinyin": "yimucao",
    "name": "益母草"
  }, {
    "pinyin": "wanxiangyu",
    "name": "晚香玉"
  }, {
    "pinyin": "jiu",
    "name": "韭"
  }, {
    "pinyin": "xiangfuzi",
    "name": "香附子"
  }, {
    "pinyin": "yinbaiyang",
    "name": "银白杨"
  }, {
    "pinyin": "huameicao",
    "name": "画眉草"
  }, {
    "pinyin": "wujiu",
    "name": "乌桕"
  }, {
    "pinyin": "huojushu",
    "name": "火炬树"
  }, {
    "pinyin": "qiufeng",
    "name": "秋枫"
  }, {
    "pinyin": "tengluo",
    "name": "藤萝"
  }, {
    "pinyin": "danbanyuejihua",
    "name": "单瓣月季花"
  }, {
    "pinyin": "shengcai",
    "name": "生菜"
  }, {
    "pinyin": "jinwawaxuancao",
    "name": "金娃娃萱草"
  }, {
    "pinyin": "lichang",
    "name": "鳢肠"
  }, {
    "pinyin": "mengguli",
    "name": "蒙古栎"
  }, {
    "pinyin": "huilüli",
    "name": "灰绿藜"
  }, {
    "pinyin": "furongkui",
    "name": "芙蓉葵"
  }, {
    "pinyin": "huanghuazuojiangcao",
    "name": "黄花酢浆草"
  }, {
    "pinyin": "xiaoyehuangyang",
    "name": "小叶黄杨"
  }, {
    "pinyin": "tiekuaizi",
    "name": "铁筷子"
  }, {
    "pinyin": "dahuamachixian",
    "name": "大花马齿苋"
  }, {
    "pinyin": "yindurong",
    "name": "印度榕"
  }, {
    "pinyin": "xuancao",
    "name": "萱草"
  }, {
    "pinyin": "gu",
    "name": "菰"
  }, {
    "pinyin": "tianlanxiuqiu",
    "name": "天蓝绣球"
  }, {
    "pinyin": "caocaosu",
    "name": "草糙苏"
  }, {
    "pinyin": "shouguanteng",
    "name": "首冠藤"
  }, {
    "pinyin": "yinwei",
    "name": "银薇"
  }, {
    "pinyin": "dayezuiyucao",
    "name": "大叶醉鱼草"
  }, {
    "pinyin": "daogenliao",
    "name": "倒根蓼"
  }, {
    "pinyin": "huangshandujuan",
    "name": "黄山杜鹃"
  }, {
    "pinyin": "hanqin",
    "name": "旱芹"
  }, {
    "pinyin": "sanyeweilingcai",
    "name": "三叶委陵菜"
  }, {
    "pinyin": "shukui",
    "name": "蜀葵"
  }, {
    "pinyin": "yinlan",
    "name": "银兰"
  }, {
    "pinyin": "gualou",
    "name": "栝楼"
  }, {
    "pinyin": "huangshuixian",
    "name": "黄水仙"
  }, {
    "pinyin": "xiaoshanju",
    "name": "小山菊"
  }, {
    "pinyin": "chesangzi",
    "name": "车桑子"
  }, {
    "pinyin": "hanxiucao",
    "name": "含羞草"
  }, {
    "pinyin": "shuikumai",
    "name": "水苦荬"
  }, {
    "pinyin": "cheqian",
    "name": "车前"
  }, {
    "pinyin": "yemianhua",
    "name": "野棉花"
  }, {
    "pinyin": "liusubeimulan",
    "name": "流苏贝母兰"
  }, {
    "pinyin": "huadongtangsongcao",
    "name": "华东唐松草"
  }, {
    "pinyin": "xiazhicao",
    "name": "夏至草"
  }, {
    "pinyin": "ruju",
    "name": "乳苣"
  }, {
    "pinyin": "luanshu",
    "name": "栾树"
  }, {
    "pinyin": "jinjiju",
    "name": "金鸡菊"
  }, {
    "pinyin": "tianrenju",
    "name": "天人菊"
  }, {
    "pinyin": "ouxuanhua",
    "name": "欧旋花"
  }, {
    "pinyin": "tianzhu",
    "name": "甜槠"
  }, {
    "pinyin": "xiaxuepianlian",
    "name": "夏雪片莲"
  }, {
    "pinyin": "shuli",
    "name": "鼠李"
  }, {
    "pinyin": "yuanyeshuli",
    "name": "圆叶鼠李"
  }, {
    "pinyin": "pizhenxinyuejue",
    "name": "披针新月蕨"
  }, {
    "pinyin": "kudouzi",
    "name": "苦豆子"
  }, {
    "pinyin": "gouji",
    "name": "构棘"
  }, {
    "pinyin": "yunbo",
    "name": "榅桲"
  }, {
    "pinyin": "chengliu",
    "name": "柽柳"
  }, {
    "pinyin": "dao",
    "name": "稻"
  }, {
    "pinyin": "xiaotianlanxiuqiu",
    "name": "小天蓝绣球"
  }, {
    "pinyin": "ziyechouli",
    "name": "紫叶稠李"
  }, {
    "pinyin": "shanputao",
    "name": "山葡萄"
  }, {
    "pinyin": "caodifengmaoju",
    "name": "草地风毛菊"
  }, {
    "pinyin": "xubaoshizhu",
    "name": "须苞石竹"
  }, {
    "pinyin": "hongbeigui",
    "name": "红背桂"
  }, {
    "pinyin": "louhao",
    "name": "蒌蒿"
  }, {
    "pinyin": "fufangteng",
    "name": "扶芳藤"
  }, {
    "pinyin": "huangzhang",
    "name": "黄樟"
  }, {
    "pinyin": "hujisheng",
    "name": "槲寄生"
  }, {
    "pinyin": "yinxing",
    "name": "银杏"
  }, {
    "pinyin": "chuiliu",
    "name": "垂柳"
  }, {
    "pinyin": "huaqiushu",
    "name": "花楸树"
  }, {
    "pinyin": "chuiyerong",
    "name": "垂叶榕"
  }, {
    "pinyin": "zhongyangmu",
    "name": "重阳木"
  }, {
    "pinyin": "qizihua",
    "name": "七子花"
  }, {
    "pinyin": "chuizhiyu",
    "name": "垂枝榆"
  }, {
    "pinyin": "lüyehuzhizi",
    "name": "绿叶胡枝子"
  }, {
    "pinyin": "zhangegualou",
    "name": "长萼栝楼"
  }, {
    "pinyin": "juhua",
    "name": "菊花"
  }, {
    "pinyin": "yinianpeng",
    "name": "一年蓬"
  }, {
    "pinyin": "lingxiao",
    "name": "凌宵"
  }, {
    "pinyin": "feizhouziluolan",
    "name": "非洲紫罗兰"
  }, {
    "pinyin": "muju",
    "name": "母菊"
  }, {
    "pinyin": "saosihua",
    "name": "缫丝花"
  }, {
    "pinyin": "shizijiashu",
    "name": "十字架树"
  }, {
    "pinyin": "jinhuacha",
    "name": "金花茶"
  }, {
    "pinyin": "guiyeshanqianniu",
    "name": "桂叶山牵牛"
  }, {
    "pinyin": "xiaoyenüzhen",
    "name": "小叶女贞"
  }, {
    "pinyin": "shidiaobo",
    "name": "石刁柏"
  }, {
    "pinyin": "chishan",
    "name": "池杉"
  }, {
    "pinyin": "lujiaozhui",
    "name": "鹿角锥"
  }, {
    "pinyin": "maoyingtao",
    "name": "毛樱桃"
  }, {
    "pinyin": "banfenghe",
    "name": "半枫荷"
  }, {
    "pinyin": "jinqianpu",
    "name": "金钱蒲"
  }, {
    "pinyin": "tianzhukui",
    "name": "天竺葵"
  }, {
    "pinyin": "shuishirong",
    "name": "水石榕"
  }, {
    "pinyin": "guoshanjue",
    "name": "过山蕨"
  }, {
    "pinyin": "ribenduying",
    "name": "日本杜英"
  }, {
    "pinyin": "jinbianlongshelan",
    "name": "金边龙舌兰"
  }, {
    "pinyin": "chuncai",
    "name": "莼菜"
  }, {
    "pinyin": "zimuxu",
    "name": "紫苜蓿"
  }, {
    "pinyin": "niumaozhan",
    "name": "牛毛毡"
  }, {
    "pinyin": "dongyatangsongcao",
    "name": "东亚唐松草"
  }, {
    "pinyin": "aertaigouwahua",
    "name": "阿尔泰狗娃花"
  }, {
    "pinyin": "yecaomei",
    "name": "野草莓"
  }, {
    "pinyin": "nansheteng",
    "name": "南蛇藤"
  }, {
    "pinyin": "yuanzhuixiuqiu",
    "name": "圆锥绣球"
  }, {
    "pinyin": "lanyerendong",
    "name": "蓝叶忍冬"
  }, {
    "pinyin": "maoershi",
    "name": "猫儿屎"
  }, {
    "pinyin": "yeyingchun",
    "name": "野迎春"
  }, {
    "pinyin": "shanzha",
    "name": "山楂"
  }, {
    "pinyin": "ribenjindaihua",
    "name": "日本锦带花"
  }, {
    "pinyin": "shegan",
    "name": "射干"
  }, {
    "pinyin": "shiliu",
    "name": "石榴"
  }, {
    "pinyin": "pipa",
    "name": "枇杷"
  }, {
    "pinyin": "xinanweimao",
    "name": "西南卫矛"
  }, {
    "pinyin": "hongwangzijindaihua",
    "name": "红王子锦带花"
  }, {
    "pinyin": "zhujieliao",
    "name": "竹节蓼"
  }, {
    "pinyin": "lishihe",
    "name": "李氏禾"
  }, {
    "pinyin": "tingchangpu",
    "name": "庭菖蒲"
  }, {
    "pinyin": "shiganzi",
    "name": "石柑子"
  }, {
    "pinyin": "shanhuangma",
    "name": "山黄麻"
  }, {
    "pinyin": "ribenliushan",
    "name": "日本柳杉"
  }, {
    "pinyin": "yizhihuanghua",
    "name": "一枝黄花"
  }, {
    "pinyin": "juyu",
    "name": "菊芋"
  }, {
    "pinyin": "shuitongmu",
    "name": "水同木"
  }, {
    "pinyin": "ziwei",
    "name": "紫薇"
  }, {
    "pinyin": "shuilashu",
    "name": "水蜡树"
  }, {
    "pinyin": "dacheqian",
    "name": "大车前"
  }, {
    "pinyin": "wenshulan",
    "name": "文殊兰"
  }, {
    "pinyin": "chouli",
    "name": "稠李"
  }, {
    "pinyin": "chiguoyoushu",
    "name": "翅果油树"
  }, {
    "pinyin": "beiyewandou",
    "name": "北野豌豆"
  }, {
    "pinyin": "ciwujia",
    "name": "刺五加"
  }, {
    "pinyin": "bankuzhu",
    "name": "斑苦竹"
  }, {
    "pinyin": "jingtiao",
    "name": "荆条"
  }, {
    "pinyin": "taohuaxinmu",
    "name": "桃花心木"
  }, {
    "pinyin": "mulan",
    "name": "木榄"
  }, {
    "pinyin": "huili",
    "name": "灰莉"
  }, {
    "pinyin": "rongshu",
    "name": "榕树"
  }, {
    "pinyin": "lüyushu",
    "name": "绿玉树"
  }, {
    "pinyin": "zisuihuai",
    "name": "紫穗槐"
  }, {
    "pinyin": "daodiaobi",
    "name": "倒吊笔"
  }, {
    "pinyin": "diedou",
    "name": "蝶豆"
  }, {
    "pinyin": "zao",
    "name": "枣"
  }, {
    "pinyin": "renmianzi",
    "name": "人面子"
  }, {
    "pinyin": "ciqiu",
    "name": "刺楸"
  }, {
    "pinyin": "jijishu",
    "name": "基及树"
  }, {
    "pinyin": "ouzhoubaiyu",
    "name": "欧洲白榆"
  }, {
    "pinyin": "chunyu",
    "name": "春榆"
  }, {
    "pinyin": "heliandoucao",
    "name": "荷莲豆草"
  }, {
    "pinyin": "qianjinyu",
    "name": "千金榆"
  }, {
    "pinyin": "baihuapaotong",
    "name": "白花泡桐"
  }, {
    "pinyin": "guazijin",
    "name": "瓜子金"
  }, {
    "pinyin": "xuepifeng",
    "name": "血皮枫"
  }, {
    "pinyin": "huangtan",
    "name": "黄檀"
  }, {
    "pinyin": "shibanmu",
    "name": "石斑木"
  }, {
    "pinyin": "xiangcao",
    "name": "象草"
  }, {
    "pinyin": "yangyu",
    "name": "阳芋"
  }, {
    "pinyin": "wulianmei",
    "name": "乌蔹莓"
  }, {
    "pinyin": "qingma",
    "name": "苘麻"
  }, {
    "pinyin": "kangduan",
    "name": "糠椴"
  }, {
    "pinyin": "qiantoubo",
    "name": "千头柏"
  }, {
    "pinyin": "dusong",
    "name": "杜松"
  }, {
    "pinyin": "xuanfuhua",
    "name": "旋覆花"
  }, {
    "pinyin": "moxigeshuweicao",
    "name": "墨西哥鼠尾草"
  }, {
    "pinyin": "ouyaxuanfuhua",
    "name": "欧亚旋覆花"
  }, {
    "pinyin": "baitan",
    "name": "白檀"
  }, {
    "pinyin": "qingfengteng",
    "name": "清风藤"
  }, {
    "pinyin": "beijingdingxiang",
    "name": "北京丁香"
  }, {
    "pinyin": "goushu",
    "name": "构树"
  }, {
    "pinyin": "mubanxia",
    "name": "木半夏"
  }, {
    "pinyin": "qianqucai",
    "name": "千屈菜"
  }, {
    "pinyin": "erseboluomi",
    "name": "二色波罗蜜"
  }, {
    "pinyin": "huangqi",
    "name": "黄杞"
  }, {
    "pinyin": "yuanbaofeng",
    "name": "元宝枫"
  }, {
    "pinyin": "nanmu",
    "name": "楠木"
  }, {
    "pinyin": "jiangguotaicao",
    "name": "浆果薹草"
  }, {
    "pinyin": "ludoushu",
    "name": "露兜树"
  }, {
    "pinyin": "eerli",
    "name": "鹅耳枥"
  }, {
    "pinyin": "citong",
    "name": "刺桐"
  }, {
    "pinyin": "quancan",
    "name": "拳参"
  }, {
    "pinyin": "zhimu",
    "name": "知母"
  }, {
    "pinyin": "yejiu",
    "name": "野韭"
  }, {
    "pinyin": "shuanchiweimao",
    "name": "栓翅卫矛"
  }, {
    "pinyin": "gouyagen",
    "name": "狗牙根"
  }, {
    "pinyin": "zhejiangrunnan",
    "name": "浙江润楠"
  }, {
    "pinyin": "bairiqing",
    "name": "百日青"
  }, {
    "pinyin": "yanmai",
    "name": "燕麦"
  }, {
    "pinyin": "ouzhoufengweijue",
    "name": "欧洲凤尾蕨"
  }, {
    "pinyin": "houelingxiao",
    "name": "厚萼凌霄"
  }, {
    "pinyin": "wuyuyu",
    "name": "乌羽玉"
  }, {
    "pinyin": "huananwuyu",
    "name": "华南吴萸"
  }, {
    "pinyin": "ruichihuli",
    "name": "锐齿槲栎"
  }, {
    "pinyin": "dayeguiying",
    "name": "大叶桂樱"
  }, {
    "pinyin": "chengchuishu",
    "name": "秤锤树"
  }, {
    "pinyin": "liangyehouerhuan",
    "name": "亮叶猴耳环"
  }, {
    "pinyin": "xianmao",
    "name": "仙茅"
  }, {
    "pinyin": "nansuanzao",
    "name": "南酸枣"
  }, {
    "pinyin": "cikao",
    "name": "刺栲"
  }, {
    "pinyin": "hainanhongdou",
    "name": "海南红豆"
  }, {
    "pinyin": "gemu",
    "name": "格木"
  }, {
    "pinyin": "yarong",
    "name": "雅榕"
  }, {
    "pinyin": "wuhuanzi",
    "name": "无患子"
  }, {
    "pinyin": "choulengshan",
    "name": "臭冷杉"
  }, {
    "pinyin": "yingqilin",
    "name": "樱麒麟"
  }, {
    "pinyin": "huanghuameirenjiao",
    "name": "黄花美人蕉"
  }, {
    "pinyin": "fenmeirenjiao",
    "name": "粉美人蕉"
  }, {
    "pinyin": "dahuameirenjiao",
    "name": "大花美人蕉"
  }, {
    "pinyin": "xixian",
    "name": "豨莶"
  }, {
    "pinyin": "qingtan",
    "name": "青檀"
  }, {
    "pinyin": "lanzhoubaihe",
    "name": "兰州百合"
  }, {
    "pinyin": "huobahua",
    "name": "火把花"
  }, {
    "pinyin": "feicai",
    "name": "费菜"
  }, {
    "pinyin": "xiaoli",
    "name": "小藜"
  }, {
    "pinyin": "fenzizhongbanmujin",
    "name": "粉紫重瓣木槿"
  }, {
    "pinyin": "lanzhuer",
    "name": "蓝猪耳"
  }, {
    "pinyin": "zhangyetiejiaojue",
    "name": "长叶铁角蕨"
  }, {
    "pinyin": "huayeluzhu",
    "name": "花叶芦竹"
  }, {
    "pinyin": "lanhuadan",
    "name": "蓝花丹"
  }, {
    "pinyin": "you",
    "name": "柚"
  }, {
    "pinyin": "toushizhu",
    "name": "头石竹"
  }, {
    "pinyin": "fozhu",
    "name": "佛珠"
  }, {
    "pinyin": "mayingdan",
    "name": "马缨丹"
  }, {
    "pinyin": "qibanlian",
    "name": "七瓣莲"
  }, {
    "pinyin": "caoshaoyao",
    "name": "草芍药"
  }, {
    "pinyin": "rujiangdaji",
    "name": "乳浆大戟"
  }, {
    "pinyin": "lingyexiuxianju",
    "name": "菱叶绣线菊"
  }, {
    "pinyin": "yingshu",
    "name": "楹树"
  }, {
    "pinyin": "langyaweilingcai",
    "name": "狼牙委陵菜"
  }, {
    "pinyin": "huanghuaren",
    "name": "黄花稔"
  }, {
    "pinyin": "chiguoju",
    "name": "翅果菊"
  }, {
    "pinyin": "kuanyesutie",
    "name": "宽叶苏铁"
  }, {
    "pinyin": "qiuguojincai",
    "name": "球果堇菜"
  }, {
    "pinyin": "ningtiaojinjier",
    "name": "柠条锦鸡儿"
  }, {
    "pinyin": "jiulian",
    "name": "韭莲"
  }, {
    "pinyin": "qianbankui",
    "name": "千瓣葵"
  }, {
    "pinyin": "xinganshengma",
    "name": "兴安升麻"
  }, {
    "pinyin": "qingxiang",
    "name": "青葙"
  }, {
    "pinyin": "jialongtouhua",
    "name": "假龙头花"
  }, {
    "pinyin": "biguancao",
    "name": "笔管草"
  }, {
    "pinyin": "yanjiecao",
    "name": "沿阶草"
  }, {
    "pinyin": "kucao",
    "name": "苦草"
  }, {
    "pinyin": "dahuanuomitiao",
    "name": "大花糯米条"
  }, {
    "pinyin": "zhanzhishacan",
    "name": "展枝沙参"
  }, {
    "pinyin": "dahuaqiukui",
    "name": "大花秋葵"
  }, {
    "pinyin": "jianqiuluo",
    "name": "剪秋罗"
  }, {
    "pinyin": "tiepishihu",
    "name": "铁皮石斛"
  }, {
    "pinyin": "jini",
    "name": "荠苨"
  }, {
    "pinyin": "daiguocao",
    "name": "袋果草"
  }, {
    "pinyin": "hangzishao",
    "name": "杭子梢"
  }, {
    "pinyin": "huabeixiuxianju",
    "name": "华北绣线菊"
  }, {
    "pinyin": "jumai",
    "name": "瞿麦"
  }, {
    "pinyin": "dawuliqinjiao",
    "name": "达乌里秦艽"
  }, {
    "pinyin": "liulan",
    "name": "柳兰"
  }, {
    "pinyin": "shebianju",
    "name": "蛇鞭菊"
  }, {
    "pinyin": "shuimachi",
    "name": "水马齿"
  }, {
    "pinyin": "quemeiteng",
    "name": "雀梅藤"
  }, {
    "pinyin": "huyang",
    "name": "胡杨"
  }, {
    "pinyin": "binmuhuan",
    "name": "滨木患"
  }, {
    "pinyin": "xinjiangrendong",
    "name": "新疆忍冬"
  }, {
    "pinyin": "fanguorendong",
    "name": "繁果忍冬"
  }, {
    "pinyin": "yanbaijiang",
    "name": "岩败酱"
  }, {
    "pinyin": "beichaihu",
    "name": "北柴胡"
  }, {
    "pinyin": "ranghe",
    "name": "蘘荷"
  }, {
    "pinyin": "hancai",
    "name": "蔊菜"
  }, {
    "pinyin": "shili",
    "name": "石栗"
  }, {
    "pinyin": "qianrihong",
    "name": "千日红"
  }, {
    "pinyin": "shenjue",
    "name": "肾蕨"
  }, {
    "pinyin": "dahuawuyaguo",
    "name": "大花五桠果"
  }, {
    "pinyin": "hulu",
    "name": "葫芦"
  }, {
    "pinyin": "qiuhuabaochun",
    "name": "球花报春"
  }, {
    "pinyin": "jianweiyu",
    "name": "尖尾芋"
  }, {
    "pinyin": "songxia",
    "name": "松霞"
  }, {
    "pinyin": "dayeluodishenggen",
    "name": "大叶落地生根"
  }, {
    "pinyin": "youshi",
    "name": "油柿"
  }, {
    "pinyin": "huaqigan",
    "name": "花旗杆"
  }, {
    "pinyin": "tingli",
    "name": "葶苈"
  }, {
    "pinyin": "danzhuye",
    "name": "淡竹叶"
  }, {
    "pinyin": "chuixushanglu",
    "name": "垂序商陆"
  }, {
    "pinyin": "yuganzi",
    "name": "余甘子"
  }, {
    "pinyin": "tiangelüzi",
    "name": "田葛缕子"
  }, {
    "pinyin": "huaxiacigu",
    "name": "华夏慈姑"
  }, {
    "pinyin": "weiganju",
    "name": "微甘菊"
  }, {
    "pinyin": "baibu",
    "name": "百部"
  }, {
    "pinyin": "fenglingcao",
    "name": "风铃草"
  }, {
    "pinyin": "fengxiangshu",
    "name": "风箱树"
  }, {
    "pinyin": "huanghuahao",
    "name": "黄花蒿"
  }, {
    "pinyin": "yandijianpeng",
    "name": "盐地碱蓬"
  }, {
    "pinyin": "kafeihuangkui",
    "name": "咖啡黄葵"
  }, {
    "pinyin": "xiangchun",
    "name": "香椿"
  }, {
    "pinyin": "haijinsha",
    "name": "海金沙"
  }, {
    "pinyin": "jiangdou",
    "name": "豇豆"
  }, {
    "pinyin": "lücao",
    "name": "葎草"
  }, {
    "pinyin": "tiannühua",
    "name": "天女花"
  }, {
    "pinyin": "wulanmu",
    "name": "乌榄木"
  }, {
    "pinyin": "mengsang",
    "name": "蒙桑"
  }, {
    "pinyin": "kupiteng",
    "name": "苦皮藤"
  }, {
    "pinyin": "xiaoyecen",
    "name": "小叶梣"
  }, {
    "pinyin": "ciguogancao",
    "name": "刺果甘草"
  }, {
    "pinyin": "zhuma",
    "name": "苎麻"
  }, {
    "pinyin": "meilirizhonghua",
    "name": "美丽日中花"
  }, {
    "pinyin": "baihuajiazhutao",
    "name": "白花夹竹桃"
  }, {
    "pinyin": "dengxincao",
    "name": "灯心草"
  }, {
    "pinyin": "lanhuacao",
    "name": "蓝花草"
  }, {
    "pinyin": "zhima",
    "name": "芝麻"
  }, {
    "pinyin": "yexing",
    "name": "野杏"
  }, {
    "pinyin": "fenbaosuanjiaogan",
    "name": "粉苞酸脚杆"
  }, {
    "pinyin": "xigua",
    "name": "西瓜"
  }, {
    "pinyin": "yushandou",
    "name": "羽扇豆"
  }, {
    "pinyin": "lanyangmao",
    "name": "蓝羊茅"
  }, {
    "pinyin": "jinxiuxian",
    "name": "锦绣苋"
  }, {
    "pinyin": "luoyushan",
    "name": "落羽杉"
  }, {
    "pinyin": "zhongguoshisuan",
    "name": "中国石蒜"
  }, {
    "pinyin": "caohaitong",
    "name": "草海桐"
  }, {
    "pinyin": "banmao",
    "name": "斑茅"
  }, {
    "pinyin": "shenertangzhu",
    "name": "肾耳唐竹"
  }, {
    "pinyin": "foduzhu",
    "name": "佛肚竹"
  }, {
    "pinyin": "jiazhutao",
    "name": "夹竹桃"
  }, {
    "pinyin": "dijin",
    "name": "地锦"
  }, {
    "pinyin": "hubeicen",
    "name": "湖北梣"
  }, {
    "pinyin": "shisong",
    "name": "石松"
  }, {
    "pinyin": "zhangchunhua",
    "name": "长春花"
  }, {
    "pinyin": "haizao",
    "name": "海枣"
  }, {
    "pinyin": "huanglan",
    "name": "黄兰"
  }, {
    "pinyin": "hongliao",
    "name": "红蓼"
  }, {
    "pinyin": "bairiju",
    "name": "百日菊"
  }, {
    "pinyin": "xiuxianju",
    "name": "绣线菊"
  }, {
    "pinyin": "hongsang",
    "name": "红桑"
  }, {
    "pinyin": "hongmaocao",
    "name": "红毛草"
  }, {
    "pinyin": "qinghao",
    "name": "青蒿"
  }, {
    "pinyin": "wucaisu",
    "name": "五彩苏"
  }, {
    "pinyin": "an",
    "name": "桉"
  }, {
    "pinyin": "zhangbaiyulinyunshan",
    "name": "长白鱼鳞云杉"
  }, {
    "pinyin": "jiguanhua",
    "name": "鸡冠花"
  }, {
    "pinyin": "taiwanxiangsi",
    "name": "台湾相思"
  }, {
    "pinyin": "aishixiangchacai",
    "name": "艾氏香茶菜"
  }, {
    "pinyin": "geluofeng",
    "name": "葛罗枫"
  }, {
    "pinyin": "luzhu",
    "name": "芦竹"
  }, {
    "pinyin": "mizhu",
    "name": "米槠"
  }, {
    "pinyin": "jianyu",
    "name": "碱菀"
  }, {
    "pinyin": "yangchangchunteng",
    "name": "洋常春藤"
  }, {
    "pinyin": "cimaodujuan",
    "name": "刺毛杜鹃"
  }, {
    "pinyin": "guizhoushinan",
    "name": "贵州石楠"
  }, {
    "pinyin": "zhuyehuajiao",
    "name": "竹叶花椒"
  }, {
    "pinyin": "taiwanrong",
    "name": "台湾榕"
  }, {
    "pinyin": "chunyehuajiao",
    "name": "椿叶花椒"
  }, {
    "pinyin": "liuyemabiancao",
    "name": "柳叶马鞭草"
  }, {
    "pinyin": "rongyexiaozhuyu",
    "name": "绒叶肖竹芋"
  }, {
    "pinyin": "heimaicao",
    "name": "黑麦草"
  }, {
    "pinyin": "chunlan",
    "name": "春兰"
  }, {
    "pinyin": "jinbiandiaolan",
    "name": "金边吊兰"
  }, {
    "pinyin": "hanlan",
    "name": "寒兰"
  }, {
    "pinyin": "longxueshu",
    "name": "龙血树"
  }, {
    "pinyin": "citongcao",
    "name": "刺通草"
  }, {
    "pinyin": "changchunteng",
    "name": "常春藤"
  }, {
    "pinyin": "zijing",
    "name": "紫茎"
  }, {
    "pinyin": "qingganyang",
    "name": "青甘杨"
  }, {
    "pinyin": "duanshu",
    "name": "椴树"
  }, {
    "pinyin": "yuehua",
    "name": "岳桦"
  }, {
    "pinyin": "shaohualongkui",
    "name": "少花龙葵"
  }, {
    "pinyin": "haitang",
    "name": "海棠"
  }, {
    "pinyin": "shuangjiajueming",
    "name": "双荚决明"
  }, {
    "pinyin": "daodiling",
    "name": "倒地铃"
  }, {
    "pinyin": "jianadayizhihuanghua",
    "name": "加拿大一枝黄花"
  }, {
    "pinyin": "shanliuju",
    "name": "山柳菊"
  }, {
    "pinyin": "duohuacuilan",
    "name": "多花脆兰"
  }, {
    "pinyin": "jianpeng",
    "name": "碱蓬"
  }, {
    "pinyin": "xiyeyimucao",
    "name": "细叶益母草"
  }, {
    "pinyin": "zancai",
    "name": "錾菜"
  }, {
    "pinyin": "ziyu",
    "name": "紫菀"
  }, {
    "pinyin": "xinyezhugecai",
    "name": "心叶诸葛菜"
  }, {
    "pinyin": "fangumaxianhao",
    "name": "返顾马先蒿"
  }, {
    "pinyin": "qingfenghuang",
    "name": "青凤凰"
  }, {
    "pinyin": "yuyiganlan",
    "name": "羽衣甘蓝"
  }, {
    "pinyin": "jiapingpo",
    "name": "假苹婆"
  }, {
    "pinyin": "haizhouchangshan",
    "name": "海州常山"
  }, {
    "pinyin": "ziyezuojiangcao",
    "name": "紫叶酢浆草"
  }, {
    "pinyin": "pingshu",
    "name": "瓶树"
  }, {
    "pinyin": "zajiaoezhangqiu",
    "name": "杂交鹅掌楸"
  }, {
    "pinyin": "jianadazijing",
    "name": "加拿大紫荆"
  }, {
    "pinyin": "xiali",
    "name": "夏栎"
  }, {
    "pinyin": "dagencaoshelan",
    "name": "大根槽舌兰"
  }, {
    "pinyin": "shanguaizao",
    "name": "山拐枣"
  }, {
    "pinyin": "chatiaomu",
    "name": "茶条木"
  }, {
    "pinyin": "meiguoshanhetao",
    "name": "美国山核桃"
  }, {
    "pinyin": "jiexiang",
    "name": "结香"
  }, {
    "pinyin": "fupenzi",
    "name": "覆盆子"
  }, {
    "pinyin": "feieshu",
    "name": "飞蛾树"
  }, {
    "pinyin": "ainaxiang",
    "name": "艾纳香"
  }, {
    "pinyin": "hualuomo",
    "name": "华萝藦"
  }, {
    "pinyin": "hanjinlian",
    "name": "旱金莲"
  }, {
    "pinyin": "honghuaxifanlian",
    "name": "红花西番莲"
  }, {
    "pinyin": "huoji",
    "name": "火棘"
  }, {
    "pinyin": "jinqiansong",
    "name": "金钱松"
  }, {
    "pinyin": "dahuaqianniu",
    "name": "大花牵牛"
  }, {
    "pinyin": "sajinbo",
    "name": "洒金柏"
  }, {
    "pinyin": "ziluolan",
    "name": "紫罗兰"
  }, {
    "pinyin": "qiansuigu",
    "name": "千穗谷"
  }, {
    "pinyin": "baochunshihu",
    "name": "报春石斛"
  }, {
    "pinyin": "doubanlü",
    "name": "豆瓣绿"
  }, {
    "pinyin": "jiemaoefengxianhua",
    "name": "睫毛萼凤仙花"
  }, {
    "pinyin": "zihuaxiangru",
    "name": "紫花香薷"
  }, {
    "pinyin": "masang",
    "name": "马桑"
  }, {
    "pinyin": "jiujielong",
    "name": "九节龙"
  }, {
    "pinyin": "zhanghuatianmendong",
    "name": "长花天门冬"
  }, {
    "pinyin": "zhonghuashinan",
    "name": "中华石楠"
  }, {
    "pinyin": "dongfengcai",
    "name": "东风菜"
  }, {
    "pinyin": "maomachixian",
    "name": "毛马齿苋"
  }, {
    "pinyin": "liuchuhua",
    "name": "六出花"
  }, {
    "pinyin": "dahewanglan",
    "name": "大鹤望兰"
  }, {
    "pinyin": "huayeqingmu",
    "name": "花叶青木"
  }, {
    "pinyin": "qipanshacao",
    "name": "畦畔莎草"
  }, {
    "pinyin": "zhuyu",
    "name": "竹芋"
  }, {
    "pinyin": "hongzhua",
    "name": "红爪"
  }, {
    "pinyin": "laoer",
    "name": "劳尔"
  }, {
    "pinyin": "shuiguijiao",
    "name": "水鬼蕉"
  }, {
    "pinyin": "guayeju",
    "name": "瓜叶菊"
  }, {
    "pinyin": "pubaohua",
    "name": "蒲包花"
  }, {
    "pinyin": "cong",
    "name": "葱"
  }, {
    "pinyin": "xiaocuiyun",
    "name": "小翠云"
  }, {
    "pinyin": "wucaiyu",
    "name": "五彩芋"
  }, {
    "pinyin": "lamei",
    "name": "蜡梅"
  }, {
    "pinyin": "yuanxianqueshemu",
    "name": "缘腺雀舌木"
  }, {
    "pinyin": "yanzizhang",
    "name": "燕子掌"
  }, {
    "pinyin": "xihuabajiaofeng",
    "name": "稀花八角枫"
  }, {
    "pinyin": "lujumu",
    "name": "栌菊木"
  }, {
    "pinyin": "shancha",
    "name": "山茶"
  }, {
    "pinyin": "aizishan",
    "name": "矮紫杉"
  }, {
    "pinyin": "qingcai",
    "name": "青菜"
  }, {
    "pinyin": "baicai",
    "name": "白菜"
  }, {
    "pinyin": "huanggua",
    "name": "黄瓜"
  }, {
    "pinyin": "kuiji",
    "name": "魁蓟"
  }, {
    "pinyin": "xiangchabiaozi",
    "name": "香茶藨子"
  }, {
    "pinyin": "baihuazhongbanmujin",
    "name": "白花重瓣木槿"
  }, {
    "pinyin": "xingmei",
    "name": "杏梅"
  }, {
    "pinyin": "luole",
    "name": "罗勒"
  }, {
    "pinyin": "xiaoyuxiancao",
    "name": "小鱼仙草"
  }, {
    "pinyin": "zhentongcai",
    "name": "针筒菜"
  }, {
    "pinyin": "shuroumaoluole",
    "name": "疏柔毛罗勒"
  }, {
    "pinyin": "juechuang",
    "name": "爵床"
  }, {
    "pinyin": "shixiangru",
    "name": "石香薷"
  }, {
    "pinyin": "mugua",
    "name": "木瓜"
  }, {
    "pinyin": "chiyedongqing",
    "name": "齿叶冬青"
  }, {
    "pinyin": "lunyeputao",
    "name": "轮叶蒲桃"
  }, {
    "pinyin": "kuge",
    "name": "苦葛"
  }, {
    "pinyin": "dayetiexianlian",
    "name": "大叶铁线莲"
  }, {
    "pinyin": "yuanmaoziyu",
    "name": "缘毛紫菀"
  }, {
    "pinyin": "lüemei",
    "name": "绿萼梅"
  }, {
    "pinyin": "xiaomixingjin",
    "name": "小米星锦"
  }, {
    "pinyin": "huayechuirong",
    "name": "花叶垂榕"
  }, {
    "pinyin": "shijunzi",
    "name": "使君子"
  }, {
    "pinyin": "sanqi",
    "name": "三七"
  }, {
    "pinyin": "erqiaoyulan",
    "name": "二乔玉兰"
  }, {
    "pinyin": "nanyangying",
    "name": "南洋楹"
  }, {
    "pinyin": "dashanying",
    "name": "大山樱"
  }, {
    "pinyin": "yingchunyingtao",
    "name": "迎春樱桃"
  }, {
    "pinyin": "chuizhidayezaoying",
    "name": "垂枝大叶早樱"
  }, {
    "pinyin": "ziyulan",
    "name": "紫玉兰"
  }, {
    "pinyin": "zhushamei",
    "name": "朱砂梅"
  }, {
    "pinyin": "chuizhibitao",
    "name": "垂枝碧桃"
  }, {
    "pinyin": "sajinbitao",
    "name": "撒金碧桃"
  }, {
    "pinyin": "ribenmaoliancai",
    "name": "日本毛连菜"
  }, {
    "pinyin": "chiyebaijuanmei",
    "name": "齿叶白鹃梅"
  }, {
    "pinyin": "shanmalan",
    "name": "山马兰"
  }, {
    "pinyin": "yiyehuangancai",
    "name": "异叶黄鹌菜"
  }, {
    "pinyin": "beimeihongshan",
    "name": "北美红杉"
  }, {
    "pinyin": "laimu",
    "name": "梾木"
  }, {
    "pinyin": "mixianxiaolianqiao",
    "name": "密腺小连翘"
  }, {
    "pinyin": "weilingcai",
    "name": "委陵菜"
  }, {
    "pinyin": "zhuguohuangjin",
    "name": "珠果黄堇"
  }, {
    "pinyin": "jinqueer",
    "name": "金雀儿"
  }, {
    "pinyin": "eshu",
    "name": "莪术"
  }, {
    "pinyin": "dianmoyu",
    "name": "滇蘑芋"
  }, {
    "pinyin": "yelaixiang",
    "name": "夜来香"
  }, {
    "pinyin": "xiediaoshijutai",
    "name": "细萼吊石苣苔"
  }, {
    "pinyin": "xichiyingtao",
    "name": "细齿樱桃"
  }, {
    "pinyin": "daqinyerong",
    "name": "大琴叶榕"
  }, {
    "pinyin": "heyetiexianjue",
    "name": "荷叶铁线蕨"
  }, {
    "pinyin": "mopancao",
    "name": "磨盘草"
  }, {
    "pinyin": "yaoguo",
    "name": "腰果"
  }, {
    "pinyin": "qiuhuahanxiao",
    "name": "球花含笑"
  }, {
    "pinyin": "aitanchun",
    "name": "矮探春"
  }, {
    "pinyin": "maoyemugua",
    "name": "毛叶木瓜"
  }, {
    "pinyin": "jiaguojue",
    "name": "荚果蕨"
  }, {
    "pinyin": "cujinglinmaojue",
    "name": "粗茎鳞毛蕨"
  }, {
    "pinyin": "shenyejinyao",
    "name": "肾叶金腰"
  }, {
    "pinyin": "ribenjinyao",
    "name": "日本金腰"
  }, {
    "pinyin": "heichaihu",
    "name": "黑柴胡"
  }, {
    "pinyin": "sichuangousuanjiang",
    "name": "四川沟酸浆"
  }, {
    "pinyin": "qianliejianqiuluo",
    "name": "浅裂剪秋罗"
  }, {
    "pinyin": "lunyebabao",
    "name": "轮叶八宝"
  }, {
    "pinyin": "xiyangli",
    "name": "西洋梨"
  }, {
    "pinyin": "meirenmei",
    "name": "美人梅"
  }, {
    "pinyin": "yingtaorendong",
    "name": "樱桃忍冬"
  }, {
    "pinyin": "longzhuahuai",
    "name": "龙爪槐"
  }, {
    "pinyin": "huayecenyeqi",
    "name": "花叶梣叶槭"
  }, {
    "pinyin": "huangjinrong",
    "name": "黄金榕"
  }, {
    "pinyin": "biansuiquemai",
    "name": "扁穗雀麦"
  }, {
    "pinyin": "taxingbitao",
    "name": "塔型碧桃"
  }, {
    "pinyin": "wangzong",
    "name": "王棕"
  }, {
    "pinyin": "jinyucao",
    "name": "金鱼草"
  }, {
    "pinyin": "baihuashanbitao",
    "name": "白花山碧桃"
  }, {
    "pinyin": "guangyezihua",
    "name": "光叶子花"
  }, {
    "pinyin": "beimeiduanyesong",
    "name": "北美短叶松"
  }, {
    "pinyin": "erqiuxuanlingmu",
    "name": "二球悬铃木"
  }, {
    "pinyin": "ditancao",
    "name": "地毯草"
  }, {
    "pinyin": "sanyehaitang",
    "name": "三叶海棠"
  }, {
    "pinyin": "bianciemeiqiangwei",
    "name": "扁刺峨眉蔷薇"
  }, {
    "pinyin": "xichichouli",
    "name": "细齿稠李"
  }, {
    "pinyin": "juhao",
    "name": "菊蒿"
  }, {
    "pinyin": "gaocongzhenzhumei",
    "name": "高丛珍珠梅"
  }, {
    "pinyin": "baixueji",
    "name": "白雪姬"
  }, {
    "pinyin": "honghuajimu",
    "name": "红花檵木"
  }, {
    "pinyin": "hongleijiami",
    "name": "红蕾荚蒾"
  }, {
    "pinyin": "baidingxiang",
    "name": "白丁香"
  }, {
    "pinyin": "honghuaqi",
    "name": "红花槭"
  }, {
    "pinyin": "xiyeshacan",
    "name": "细叶沙参"
  }, {
    "pinyin": "linbizemi",
    "name": "鳞秕泽米"
  }, {
    "pinyin": "suancheng",
    "name": "酸橙"
  }, {
    "pinyin": "xiaoyehaijinsha",
    "name": "小叶海金沙"
  }, {
    "pinyin": "sheguohuangjin",
    "name": "蛇果黄堇"
  }, {
    "pinyin": "shanxibaochun",
    "name": "陕西报春"
  }, {
    "pinyin": "huanghuayexiangshu",
    "name": "黄花夜香树"
  }, {
    "pinyin": "niaoshelan",
    "name": "鸟舌兰"
  }, {
    "pinyin": "chunyunshi",
    "name": "春云实"
  }, {
    "pinyin": "jushihu",
    "name": "聚石斛"
  }, {
    "pinyin": "chuixuezhisongjin",
    "name": "吹雪之松锦"
  }, {
    "pinyin": "meihongsijihaitang",
    "name": "玫红四季海棠"
  }, {
    "pinyin": "huanggeshu",
    "name": "黄葛树"
  }, {
    "pinyin": "yushan",
    "name": "玉扇"
  }, {
    "pinyin": "fangxiangbo",
    "name": "芳香波"
  }, {
    "pinyin": "huapugongying",
    "name": "华蒲公英"
  }, {
    "pinyin": "jiantoutangsongcao",
    "name": "箭头唐松草"
  }, {
    "pinyin": "baihuamalin",
    "name": "白花马蔺"
  }, {
    "pinyin": "sanyefeng",
    "name": "三叶枫"
  }, {
    "pinyin": "dunyeqiangwei",
    "name": "钝叶蔷薇"
  }, {
    "pinyin": "maoruixiang",
    "name": "毛瑞香"
  }, {
    "pinyin": "tenghuai",
    "name": "藤槐"
  }, {
    "pinyin": "jinyingzi",
    "name": "金樱子"
  }, {
    "pinyin": "xiaokumai",
    "name": "小苦荬"
  }, {
    "pinyin": "xiaoyeqingpifeng",
    "name": "小叶青皮枫"
  }, {
    "pinyin": "duzhanchun",
    "name": "独占春"
  }, {
    "pinyin": "zibeiwannianqing",
    "name": "紫背万年青"
  }, {
    "pinyin": "aopulinna",
    "name": "奥普琳娜"
  }, {
    "pinyin": "dabaopihua",
    "name": "大豹皮花"
  }, {
    "pinyin": "baihuaganlan",
    "name": "白花甘蓝"
  }, {
    "pinyin": "niboerlaoguancao",
    "name": "尼泊尔老鹳草"
  }, {
    "pinyin": "bandengguo",
    "name": "板凳果"
  }, {
    "pinyin": "jinjijiaojialiujue",
    "name": "金鸡脚假瘤蕨"
  }, {
    "pinyin": "bianfuge",
    "name": "蝙蝠葛"
  }, {
    "pinyin": "gouweicao",
    "name": "狗尾草"
  }, {
    "pinyin": "maoputao",
    "name": "毛葡萄"
  }, {
    "pinyin": "mianmaosuanmoyeliao",
    "name": "绵毛酸模叶蓼"
  }, {
    "pinyin": "xiangliao",
    "name": "香蓼"
  }, {
    "pinyin": "liaogaoben",
    "name": "辽藁本"
  }, {
    "pinyin": "yibingchiguoju",
    "name": "翼柄翅果菊"
  }, {
    "pinyin": "badusan",
    "name": "拔毒散"
  }, {
    "pinyin": "dayejushu",
    "name": "大叶榉树"
  }, {
    "pinyin": "yunnanhongjingtian",
    "name": "云南红景天"
  }, {
    "pinyin": "huangguajiahaiyangcan",
    "name": "黄瓜假还阳参"
  }, {
    "pinyin": "muhudie",
    "name": "木蝴蝶"
  }, {
    "pinyin": "jiahaiyangcan",
    "name": "假还阳参"
  }, {
    "pinyin": "jinhehuan",
    "name": "金合欢"
  }, {
    "pinyin": "maohuanglu",
    "name": "毛黄栌"
  }, {
    "pinyin": "jibei",
    "name": "吉贝"
  }, {
    "pinyin": "yushu",
    "name": "雨树"
  }, {
    "pinyin": "gaoxuelun",
    "name": "高雪轮"
  }, {
    "pinyin": "longchuanhua",
    "name": "龙船花"
  }, {
    "pinyin": "dujuan",
    "name": "杜鹃"
  }, {
    "pinyin": "roumaodawanhua",
    "name": "柔毛打碗花"
  }, {
    "pinyin": "yinbeifengmaoju",
    "name": "银背风毛菊"
  }, {
    "pinyin": "shazao",
    "name": "沙枣"
  }, {
    "pinyin": "zhujiecan",
    "name": "竹节参"
  }, {
    "pinyin": "lianzuozijinniu",
    "name": "莲座紫金牛"
  }, {
    "pinyin": "menggufengmaoju",
    "name": "蒙古风毛菊"
  }, {
    "pinyin": "xiatianju",
    "name": "下田菊"
  }, {
    "pinyin": "bibaofengmaoju",
    "name": "篦苞风毛菊"
  }, {
    "pinyin": "xiaosheziyu",
    "name": "小舌紫菀"
  }, {
    "pinyin": "sanmaiziyu",
    "name": "三脉紫菀"
  }, {
    "pinyin": "qiuxujiu",
    "name": "球序韭"
  }, {
    "pinyin": "ercha",
    "name": "儿茶"
  }, {
    "pinyin": "zuantianyang",
    "name": "钻天杨"
  }, {
    "pinyin": "yuyedingxiang",
    "name": "羽叶丁香"
  }, {
    "pinyin": "huangmuxianghua",
    "name": "黄木香花"
  }, {
    "pinyin": "juguorong",
    "name": "聚果榕"
  }, {
    "pinyin": "yulinghua",
    "name": "玉铃花"
  }, {
    "pinyin": "tangqi",
    "name": "糖槭"
  }, {
    "pinyin": "qianlixiang",
    "name": "千里香"
  }, {
    "pinyin": "luofumaimateng",
    "name": "罗浮买麻藤"
  }, {
    "pinyin": "ketengzi",
    "name": "榼藤子"
  }, {
    "pinyin": "xixin",
    "name": "细辛"
  }, {
    "pinyin": "weizhuangyangmao",
    "name": "苇状羊茅"
  }, {
    "pinyin": "sanlengshuicong",
    "name": "三棱水葱"
  }, {
    "pinyin": "cihuai",
    "name": "刺槐"
  }, {
    "pinyin": "kuanyemucao",
    "name": "宽叶母草"
  }, {
    "pinyin": "sanchunshuibozhi",
    "name": "三春水柏枝"
  }, {
    "pinyin": "nanyudai",
    "name": "南玉带"
  }, {
    "pinyin": "duantingfeipeng",
    "name": "短葶飞蓬"
  }, {
    "pinyin": "danbansaosihua",
    "name": "单瓣缫丝花"
  }, {
    "pinyin": "xinganbaitouweng",
    "name": "兴安白头翁"
  }, {
    "pinyin": "duweicao",
    "name": "独尾草"
  }, {
    "pinyin": "niboersuanmo",
    "name": "尼泊尔酸模"
  }, {
    "pinyin": "ciqiangwei",
    "name": "刺蔷薇"
  }, {
    "pinyin": "huananrendong",
    "name": "华南忍冬"
  }, {
    "pinyin": "ai",
    "name": "艾"
  }, {
    "pinyin": "jinyudiaolan",
    "name": "金鱼吊兰"
  }, {
    "pinyin": "huangshihu",
    "name": "黄石斛"
  }, {
    "pinyin": "niboerchangchunteng",
    "name": "尼泊尔常春藤"
  }, {
    "pinyin": "shanshi",
    "name": "山柿"
  }, {
    "pinyin": "xiaoyuzhu",
    "name": "小玉竹"
  }, {
    "pinyin": "zhugenqi",
    "name": "竹根七"
  }, {
    "pinyin": "queshehuangyang",
    "name": "雀舌黄杨"
  }, {
    "pinyin": "huangguanshicao",
    "name": "皇冠蓍草"
  }, {
    "pinyin": "yuanzhuishitouhua",
    "name": "圆锥石头花"
  }, {
    "pinyin": "hudiehua",
    "name": "蝴蝶花"
  }, {
    "pinyin": "dahuacong",
    "name": "大花葱"
  }, {
    "pinyin": "maodihuang",
    "name": "毛地黄"
  }, {
    "pinyin": "hongyejinhua",
    "name": "红叶金花"
  }, {
    "pinyin": "xiaohuanghuacai",
    "name": "小黄花菜"
  }, {
    "pinyin": "baidu",
    "name": "白杜"
  }, {
    "pinyin": "feishu",
    "name": "榧树"
  }, {
    "pinyin": "lianxiangshu",
    "name": "连香树"
  }, {
    "pinyin": "hongyeshinan",
    "name": "红叶石楠"
  }, {
    "pinyin": "zhongshu",
    "name": "柊树"
  }, {
    "pinyin": "manhuasheng",
    "name": "蔓花生"
  }, {
    "pinyin": "matihe",
    "name": "马蹄荷"
  }, {
    "pinyin": "zikuang",
    "name": "紫矿"
  }, {
    "pinyin": "jiuye",
    "name": "酒椰"
  }, {
    "pinyin": "hujiao",
    "name": "胡椒"
  }, {
    "pinyin": "liulian",
    "name": "榴莲"
  }, {
    "pinyin": "tianma",
    "name": "天麻"
  }, {
    "pinyin": "yuanyenanyangcan",
    "name": "圆叶南洋参"
  }, {
    "pinyin": "mangmaojutai",
    "name": "芒毛苣苔"
  }, {
    "pinyin": "jinbeiteng",
    "name": "金杯藤"
  }, {
    "pinyin": "xianggucao",
    "name": "香菇草"
  }, {
    "pinyin": "zongzhu",
    "name": "棕竹"
  }, {
    "pinyin": "tianxiangteng",
    "name": "天香藤"
  }, {
    "pinyin": "yubiaohuai",
    "name": "鱼鳔槐"
  }, {
    "pinyin": "choumoli",
    "name": "臭茉莉"
  }, {
    "pinyin": "wenxinlan",
    "name": "文心兰"
  }, {
    "pinyin": "kanchajiafeicai",
    "name": "堪察加费菜"
  }, {
    "pinyin": "luobuma",
    "name": "罗布麻"
  }, {
    "pinyin": "qingjiangteng",
    "name": "青江藤"
  }, {
    "pinyin": "banjiuju",
    "name": "斑鸠菊"
  }, {
    "pinyin": "baifanshu",
    "name": "白饭树"
  }, {
    "pinyin": "huihuisuan",
    "name": "茴茴蒜"
  }, {
    "pinyin": "niboershuidongge",
    "name": "尼泊尔水东哥"
  }, {
    "pinyin": "saozhoucai",
    "name": "扫帚菜"
  }, {
    "pinyin": "zazhongdujuan",
    "name": "杂种杜鹃"
  }, {
    "pinyin": "lujiaodujuan",
    "name": "鹿角杜鹃"
  }, {
    "pinyin": "mayingdujuan",
    "name": "马缨杜鹃"
  }, {
    "pinyin": "gaoshandujuan",
    "name": "高山杜鹃"
  }, {
    "pinyin": "shuhuaweimao",
    "name": "疏花卫矛"
  }, {
    "pinyin": "manaoshiliu",
    "name": "玛瑙石榴"
  }, {
    "pinyin": "lunyehuangjing",
    "name": "轮叶黄精"
  }, {
    "pinyin": "liangtianchi",
    "name": "量天尺"
  }, {
    "pinyin": "tengzhangmiao",
    "name": "藤长苗"
  }, {
    "pinyin": "honghuashuilian",
    "name": "红花睡莲"
  }, {
    "pinyin": "kuojiahehuan",
    "name": "阔荚合欢"
  }, {
    "pinyin": "ciguochabiaozi",
    "name": "刺果茶藨子"
  }, {
    "pinyin": "ezuihua",
    "name": "鳄嘴花"
  }, {
    "pinyin": "xiaolikafei",
    "name": "小粒咖啡"
  }, {
    "pinyin": "gaoshanbo",
    "name": "高山柏"
  }, {
    "pinyin": "taizhu",
    "name": "泰竹"
  }, {
    "pinyin": "honghua",
    "name": "红花"
  }, {
    "pinyin": "tuerweimiao",
    "name": "兔儿尾苗"
  }, {
    "pinyin": "wujiaofeng",
    "name": "五角枫"
  }, {
    "pinyin": "xiangwandou",
    "name": "香豌豆"
  }, {
    "pinyin": "jinghuangqin",
    "name": "京黄芩"
  }, {
    "pinyin": "menggujiu",
    "name": "蒙古韭"
  }, {
    "pinyin": "shanjiu",
    "name": "山韭"
  }, {
    "pinyin": "baishanloudoucai",
    "name": "白山耧斗菜"
  }, {
    "pinyin": "guiying",
    "name": "桂樱"
  }, {
    "pinyin": "wuliemu",
    "name": "五列木"
  }, {
    "pinyin": "ribenbianbo",
    "name": "日本扁柏"
  }, {
    "pinyin": "linmu",
    "name": "橉木"
  }, {
    "pinyin": "huaxiejia",
    "name": "华蟹甲"
  }, {
    "pinyin": "tuowu",
    "name": "橐吾"
  }, {
    "pinyin": "banzhongtiexianlian",
    "name": "半钟铁线莲"
  }, {
    "pinyin": "kuanyejiu",
    "name": "宽叶韭"
  }, {
    "pinyin": "xiuqiuxiuxianju",
    "name": "绣球绣线菊"
  }, {
    "pinyin": "yingsukui",
    "name": "罂粟葵"
  }, {
    "pinyin": "shuizhucao",
    "name": "水珠草"
  }, {
    "pinyin": "tougucao",
    "name": "透骨草"
  }, {
    "pinyin": "erbaohuangjing",
    "name": "二苞黄精"
  }, {
    "pinyin": "wuzhulan",
    "name": "无柱兰"
  }, {
    "pinyin": "lingxiao",
    "name": "凌霄"
  }, {
    "pinyin": "zhangbingshanmahuang",
    "name": "长柄山蚂蝗"
  }, {
    "pinyin": "pijiancao",
    "name": "披碱草"
  }, {
    "pinyin": "liuzuodashanjingjie",
    "name": "六座大山荆芥"
  }, {
    "pinyin": "huashengdunzong",
    "name": "华盛顿棕"
  }, {
    "pinyin": "xiaoyelanren",
    "name": "小叶榄仁"
  }, {
    "pinyin": "wanglian",
    "name": "王莲"
  }, {
    "pinyin": "yejiao",
    "name": "野蕉"
  }, {
    "pinyin": "nantianzhu",
    "name": "南天竹"
  }, {
    "pinyin": "erqiaomudan",
    "name": "二乔牡丹"
  }, {
    "pinyin": "ruqie",
    "name": "乳茄"
  }, {
    "pinyin": "zilucao",
    "name": "紫露草"
  }, {
    "pinyin": "xishanjincai",
    "name": "西山堇菜"
  }, {
    "pinyin": "qinglütaicao",
    "name": "青绿薹草"
  }, {
    "pinyin": "menggujincai",
    "name": "蒙古堇菜"
  }, {
    "pinyin": "panguoju",
    "name": "盘果菊"
  }, {
    "pinyin": "chichiliao",
    "name": "齿翅蓼"
  }, {
    "pinyin": "laoyahu",
    "name": "老鸦糊"
  }, {
    "pinyin": "dahuajiu",
    "name": "大花韭"
  }, {
    "pinyin": "xiyesuihua",
    "name": "细叶穗花"
  }, {
    "pinyin": "huachangpu",
    "name": "花菖蒲"
  }, {
    "pinyin": "liuyelü",
    "name": "六叶葎"
  }, {
    "pinyin": "feilian",
    "name": "飞廉"
  }, {
    "pinyin": "jituijincai",
    "name": "鸡腿堇菜"
  }, {
    "pinyin": "diburong",
    "name": "地不容"
  }, {
    "pinyin": "maohuashengdunzong",
    "name": "毛华盛顿棕"
  }, {
    "pinyin": "shanyeludoushu",
    "name": "扇叶露兜树"
  }, {
    "pinyin": "sanweikui",
    "name": "散尾葵"
  }, {
    "pinyin": "jianalihaizao",
    "name": "加拿利海枣"
  }, {
    "pinyin": "sutiejue",
    "name": "苏铁蕨"
  }, {
    "pinyin": "longkui",
    "name": "龙葵"
  }, {
    "pinyin": "bianyemu",
    "name": "变叶木"
  }, {
    "pinyin": "caoxuejie",
    "name": "草血竭"
  }, {
    "pinyin": "wosun",
    "name": "莴笋"
  }, {
    "pinyin": "lusilan",
    "name": "鹭鸶兰"
  }, {
    "pinyin": "dahuaxijiao",
    "name": "大花犀角"
  }, {
    "pinyin": "zhouguoxian",
    "name": "皱果苋"
  }, {
    "pinyin": "huayediankucai",
    "name": "花叶滇苦菜"
  }, {
    "pinyin": "duozhichengliu",
    "name": "多枝柽柳"
  }, {
    "pinyin": "zie",
    "name": "紫萼"
  }, {
    "pinyin": "lingmu",
    "name": "柃木"
  }, {
    "pinyin": "huangcaowu",
    "name": "黄草乌"
  }, {
    "pinyin": "beijiangraohua",
    "name": "北江荛花"
  }, {
    "pinyin": "mayexiuxianju",
    "name": "麻叶绣线菊"
  }, {
    "pinyin": "hongchaihu",
    "name": "红柴胡"
  }, {
    "pinyin": "hudiexizhuhua",
    "name": "蝴蝶戏珠花"
  }, {
    "pinyin": "juyexiangli",
    "name": "菊叶香藜"
  }, {
    "pinyin": "yehuaniubinghua",
    "name": "腋花扭柄花"
  }, {
    "pinyin": "gouercha",
    "name": "勾儿茶"
  }, {
    "pinyin": "yuanzhuishanmahuang",
    "name": "圆锥山蚂蝗"
  }, {
    "pinyin": "huangjingyegouwen",
    "name": "黄精叶钩吻"
  }, {
    "pinyin": "tengshisong",
    "name": "藤石松"
  }, {
    "pinyin": "jiaweifuzimao",
    "name": "假苇拂子茅"
  }, {
    "pinyin": "dongfangxiangpu",
    "name": "东方香蒲"
  }, {
    "pinyin": "ruihe",
    "name": "蕤核"
  }, {
    "pinyin": "shaji",
    "name": "沙棘"
  }, {
    "pinyin": "xiaoyuanwei",
    "name": "肖鸢尾"
  }, {
    "pinyin": "jiupinglan",
    "name": "酒瓶兰"
  }, {
    "pinyin": "sidaicao",
    "name": "丝带草"
  }, {
    "pinyin": "gaoyangmao",
    "name": "高羊茅"
  }, {
    "pinyin": "lian",
    "name": "莲"
  }, {
    "pinyin": "zhangbanxuancao",
    "name": "长瓣萱草"
  }, {
    "pinyin": "wutong",
    "name": "梧桐"
  }, {
    "pinyin": "gougu",
    "name": "枸骨"
  }, {
    "pinyin": "fenhuaxiuxianju",
    "name": "粉花绣线菊"
  }, {
    "pinyin": "yipinhong",
    "name": "一品红"
  }, {
    "pinyin": "yinhua",
    "name": "银桦"
  }, {
    "pinyin": "yuweikui",
    "name": "鱼尾葵"
  }, {
    "pinyin": "ningmengan",
    "name": "柠檬桉"
  }, {
    "pinyin": "zaoyuanzhu",
    "name": "早园竹"
  }, {
    "pinyin": "yanfumu",
    "name": "盐肤木"
  }, {
    "pinyin": "shanhetao",
    "name": "山核桃"
  }, {
    "pinyin": "erongteng",
    "name": "鹅绒藤"
  }, {
    "pinyin": "bianfucao",
    "name": "蝙蝠草"
  }, {
    "pinyin": "maogua",
    "name": "茅瓜"
  }, {
    "pinyin": "jinhuaxiaobo",
    "name": "金花小檗"
  }, {
    "pinyin": "xiangcaique",
    "name": "香彩雀"
  }, {
    "pinyin": "yeshengdao",
    "name": "野生稻"
  }, {
    "pinyin": "xiyeyuanwei",
    "name": "细叶鸢尾"
  }, {
    "pinyin": "tianlanshuweicao",
    "name": "天蓝鼠尾草"
  }, {
    "pinyin": "jiguchangshan",
    "name": "鸡骨常山"
  }, {
    "pinyin": "caiyecao",
    "name": "彩叶草"
  }, {
    "pinyin": "heizhongcao",
    "name": "黑种草"
  }, {
    "pinyin": "wenzhu",
    "name": "文竹"
  }, {
    "pinyin": "kuoyebanzhilian",
    "name": "阔叶半枝莲"
  }, {
    "pinyin": "yeshi",
    "name": "野柿"
  }, {
    "pinyin": "huangjinfeng",
    "name": "黄金凤"
  }, {
    "pinyin": "baopihua",
    "name": "豹皮花"
  }, {
    "pinyin": "gouyahua",
    "name": "狗牙花"
  }, {
    "pinyin": "daodou",
    "name": "刀豆"
  }, {
    "pinyin": "daxiezicao",
    "name": "大蝎子草"
  }, {
    "pinyin": "nuomiduan",
    "name": "糯米椴"
  }, {
    "pinyin": "xingmeiren",
    "name": "星美人"
  }, {
    "pinyin": "shengshihua",
    "name": "生石花"
  }, {
    "pinyin": "fojiacao",
    "name": "佛甲草"
  }, {
    "pinyin": "huanghuaxinyue",
    "name": "黄花新月"
  }, {
    "pinyin": "jiamachixian",
    "name": "假马齿苋"
  }, {
    "pinyin": "luweihua",
    "name": "露薇花"
  }, {
    "pinyin": "shichetianrenju",
    "name": "矢车天人菊"
  }, {
    "pinyin": "jinguangju",
    "name": "金光菊"
  }, {
    "pinyin": "langweicao",
    "name": "狼尾草"
  }, {
    "pinyin": "mang",
    "name": "芒"
  }, {
    "pinyin": "tuchenxiang",
    "name": "土沉香"
  }, {
    "pinyin": "xizangbaochun",
    "name": "西藏报春"
  }, {
    "pinyin": "dahuajinjiju",
    "name": "大花金鸡菊"
  }, {
    "pinyin": "xiangxueqiu",
    "name": "香雪球"
  }, {
    "pinyin": "yuzhui",
    "name": "玉缀"
  }, {
    "pinyin": "luokui",
    "name": "落葵"
  }, {
    "pinyin": "daguoweimao",
    "name": "大果卫矛"
  }, {
    "pinyin": "yiqiuxuanlingmu",
    "name": "一球悬铃木"
  }, {
    "pinyin": "zimoli",
    "name": "紫茉莉"
  }, {
    "pinyin": "zhoushanxinmujiangzi",
    "name": "舟山新木姜子"
  }, {
    "pinyin": "honghuabajiao",
    "name": "红花八角"
  }, {
    "pinyin": "huaiyepin",
    "name": "槐叶蘋"
  }, {
    "pinyin": "shanmaidong",
    "name": "山麦冬"
  }, {
    "pinyin": "jinxiudujuan",
    "name": "锦绣杜鹃"
  }, {
    "pinyin": "siruipo",
    "name": "四蕊朴"
  }, {
    "pinyin": "quemai",
    "name": "雀麦"
  }, {
    "pinyin": "（duorou）hongbaoshi",
    "name": "（多肉）红宝石"
  }, {
    "pinyin": "huangjinwanniancao",
    "name": "黄金万年草"
  }, {
    "pinyin": "nüchu",
    "name": "女雏"
  }, {
    "pinyin": "taozhiluan",
    "name": "桃之卵"
  }, {
    "pinyin": "shierjuan",
    "name": "十二卷"
  }, {
    "pinyin": "feizaojia",
    "name": "肥皂荚"
  }, {
    "pinyin": "dongbeixing",
    "name": "东北杏"
  }, {
    "pinyin": "maodouli",
    "name": "帽斗栎"
  }, {
    "pinyin": "caidoushu",
    "name": "菜豆树"
  }, {
    "pinyin": "baileizhudinghong",
    "name": "白肋朱顶红"
  }, {
    "pinyin": "feizhoufurong",
    "name": "非洲芙蓉"
  }, {
    "pinyin": "chuanli",
    "name": "川梨"
  }, {
    "pinyin": "turencan",
    "name": "土人参"
  }, {
    "pinyin": "muqilin",
    "name": "木麒麟"
  }, {
    "pinyin": "bolan",
    "name": "擘蓝"
  }, {
    "pinyin": "juzijing",
    "name": "巨紫荆"
  }, {
    "pinyin": "guke",
    "name": "古柯"
  }, {
    "pinyin": "zhenzhuxiuxianju",
    "name": "珍珠绣线菊"
  }, {
    "pinyin": "youbaicai",
    "name": "油白菜"
  }, {
    "pinyin": "ji",
    "name": "荠"
  }, {
    "pinyin": "honghuayangtijia",
    "name": "红花羊蹄甲"
  }, {
    "pinyin": "rongbaoteng",
    "name": "绒苞藤"
  }, {
    "pinyin": "baijuanmei",
    "name": "白鹃梅"
  }, {
    "pinyin": "pugongying",
    "name": "蒲公英"
  }, {
    "pinyin": "baihuazhongbanmeigui",
    "name": "白花重瓣玫瑰"
  }, {
    "pinyin": "ziyemeirenjiao",
    "name": "紫叶美人蕉"
  }, {
    "pinyin": "duohuaziteng",
    "name": "多花紫藤"
  }, {
    "pinyin": "honghuacihuai",
    "name": "红花刺槐"
  }, {
    "pinyin": "niboerxiangqing",
    "name": "尼泊尔香青"
  }, {
    "pinyin": "qiyecao",
    "name": "槭叶草"
  }, {
    "pinyin": "xiaoyidianhong",
    "name": "小一点红"
  }, {
    "pinyin": "guanjiezuojiangcao",
    "name": "关节酢浆草"
  }, {
    "pinyin": "guizhuxiang",
    "name": "桂竹香"
  }, {
    "pinyin": "jiaojin",
    "name": "角堇"
  }, {
    "pinyin": "guanyinlian",
    "name": "观音莲"
  }, {
    "pinyin": "mingjing",
    "name": "明镜"
  }, {
    "pinyin": "zhiganfanxing",
    "name": "枝干番杏"
  }, {
    "pinyin": "duangengwaercao",
    "name": "短梗挖耳草"
  }, {
    "pinyin": "dahuaxuancao",
    "name": "大花萱草"
  }, {
    "pinyin": "hainanshanjiang",
    "name": "海南山姜"
  }, {
    "pinyin": "huihuisu",
    "name": "回回苏"
  }, {
    "pinyin": "niubian",
    "name": "牛扁"
  }, {
    "pinyin": "sanlieyetuncao",
    "name": "三裂叶豚草"
  }, {
    "pinyin": "jianchichoumoli",
    "name": "尖齿臭茉莉"
  }, {
    "pinyin": "choumudan",
    "name": "臭牡丹"
  }, {
    "pinyin": "shuijue",
    "name": "水蕨"
  }, {
    "pinyin": "guanyinzhu",
    "name": "观音竹"
  }, {
    "pinyin": "huazhudinghong",
    "name": "花朱顶红"
  }, {
    "pinyin": "huiqiu",
    "name": "灰楸"
  }, {
    "pinyin": "xiongercao",
    "name": "熊耳草"
  }, {
    "pinyin": "lian",
    "name": "楝"
  }, {
    "pinyin": "baizilian",
    "name": "百子莲"
  }, {
    "pinyin": "yadanzi",
    "name": "鸦胆子"
  }, {
    "pinyin": "maodanmagan",
    "name": "毛丹麻杆"
  }, {
    "pinyin": "biandou",
    "name": "扁豆"
  }, {
    "pinyin": "guangdongsigua",
    "name": "广东丝瓜"
  }, {
    "pinyin": "shanwoju",
    "name": "山莴苣"
  }, {
    "pinyin": "baomadingxiang",
    "name": "暴马丁香"
  }, {
    "pinyin": "gouzhuadou",
    "name": "狗爪豆"
  }, {
    "pinyin": "shendao",
    "name": "神刀"
  }, {
    "pinyin": "qianfoshou",
    "name": "千佛手"
  }, {
    "pinyin": "wandou",
    "name": "豌豆"
  }, {
    "pinyin": "huoxiang",
    "name": "藿香"
  }, {
    "pinyin": "lushanxiaobo",
    "name": "庐山小檗"
  }, {
    "pinyin": "xinyeqiulan",
    "name": "心叶球兰"
  }, {
    "pinyin": "yushu",
    "name": "玉树"
  }, {
    "pinyin": "bawangbian",
    "name": "霸王鞭"
  }, {
    "pinyin": "huyanwannianqing",
    "name": "虎眼万年青"
  }, {
    "pinyin": "yeyu",
    "name": "野芋"
  }, {
    "pinyin": "wuhuajiang",
    "name": "舞花姜"
  }, {
    "pinyin": "xiangxuelan",
    "name": "香雪兰"
  }, {
    "pinyin": "bima",
    "name": "蓖麻"
  }, {
    "pinyin": "mizilan",
    "name": "米仔兰"
  }, {
    "pinyin": "mulan",
    "name": "木蓝"
  }, {
    "pinyin": "shanmujing",
    "name": "山牡荆"
  }, {
    "pinyin": "yu",
    "name": "芋"
  }, {
    "pinyin": "danggui",
    "name": "当归"
  }, {
    "pinyin": "baihezhu",
    "name": "百合竹"
  }, {
    "pinyin": "maoqianniu",
    "name": "毛牵牛"
  }, {
    "pinyin": "huanghualuoyesong",
    "name": "黄花落叶松"
  }, {
    "pinyin": "huabeiluoyesong",
    "name": "华北落叶松"
  }, {
    "pinyin": "yanyechunzhujutai",
    "name": "烟叶唇柱苣苔"
  }, {
    "pinyin": "dayeyu",
    "name": "大野芋"
  }, {
    "pinyin": "kuobaoju",
    "name": "阔苞菊"
  }, {
    "pinyin": "lanhudie",
    "name": "蓝蝴蝶"
  }, {
    "pinyin": "binyurui",
    "name": "滨玉蕊"
  }, {
    "pinyin": "youdianbaihe",
    "name": "油点百合"
  }, {
    "pinyin": "diancizao",
    "name": "滇刺枣"
  }, {
    "pinyin": "suanmo",
    "name": "酸模"
  }, {
    "pinyin": "xiayefeicai",
    "name": "狭叶费菜"
  }, {
    "pinyin": "jidanhua",
    "name": "鸡蛋花"
  }, {
    "pinyin": "jialan",
    "name": "嘉兰"
  }, {
    "pinyin": "yingyedoulan",
    "name": "硬叶兜兰"
  }, {
    "pinyin": "haishizhu",
    "name": "海石竹"
  }, {
    "pinyin": "yinxingqiuhaitang",
    "name": "银星秋海棠"
  }, {
    "pinyin": "huojujiang",
    "name": "火炬姜"
  }, {
    "pinyin": "fenzhishan",
    "name": "粉纸扇"
  }, {
    "pinyin": "putongzhenmaojue",
    "name": "普通针毛蕨"
  }, {
    "pinyin": "caiji",
    "name": "菜蓟"
  }, {
    "pinyin": "nüwanghuali",
    "name": "女王花笠"
  }, {
    "pinyin": "suoyucao",
    "name": "梭鱼草"
  }, {
    "pinyin": "zibeizhuyu",
    "name": "紫背竹芋"
  }, {
    "pinyin": "yudiaozhong",
    "name": "玉吊钟"
  }, {
    "pinyin": "zhulian",
    "name": "朱莲"
  }, {
    "pinyin": "fengli",
    "name": "凤梨"
  }, {
    "pinyin": "baijingju",
    "name": "白晶菊"
  }, {
    "pinyin": "bainiao",
    "name": "白鸟"
  }, {
    "pinyin": "gaoshazhiweng",
    "name": "高砂之翁"
  }, {
    "pinyin": "yanzihua",
    "name": "燕子花"
  }, {
    "pinyin": "dizhonghaijiami",
    "name": "地中海荚蒾"
  }, {
    "pinyin": "huayeyanmaicao",
    "name": "花叶燕麦草"
  }, {
    "pinyin": "shanyezao",
    "name": "杉叶藻"
  }, {
    "pinyin": "qiumudan",
    "name": "秋牡丹"
  }, {
    "pinyin": "meiguishihu",
    "name": "玫瑰石斛"
  }, {
    "pinyin": "hongfenpuhua",
    "name": "红粉扑花"
  }, {
    "pinyin": "hongelongtuzhu",
    "name": "红萼龙吐珠"
  }, {
    "pinyin": "xiaoqiumeigui",
    "name": "小球玫瑰"
  }, {
    "pinyin": "luwei",
    "name": "芦苇"
  }, {
    "pinyin": "jinhuwei",
    "name": "金虎尾"
  }, {
    "pinyin": "yuanyangmoli",
    "name": "鸳鸯茉莉"
  }, {
    "pinyin": "zhanggenghebeijiu",
    "name": "长梗合被韭"
  }, {
    "pinyin": "baihuaniwandailan",
    "name": "白花拟万代兰"
  }, {
    "pinyin": "shanhuhua",
    "name": "珊瑚花"
  }, {
    "pinyin": "caichunfeng",
    "name": "彩春峰"
  }, {
    "pinyin": "yinlianhua",
    "name": "银莲花"
  }, {
    "pinyin": "sugentianrenju",
    "name": "宿根天人菊"
  }, {
    "pinyin": "guanghangong",
    "name": "广寒宫"
  }, {
    "pinyin": "huojuhua",
    "name": "火炬花"
  }, {
    "pinyin": "baxiyemudan",
    "name": "巴西野牡丹"
  }, {
    "pinyin": "nantonghao",
    "name": "南茼蒿"
  }, {
    "pinyin": "jianyejinjiju",
    "name": "剑叶金鸡菊"
  }, {
    "pinyin": "meiguobohe",
    "name": "美国薄荷"
  }, {
    "pinyin": "shantugua",
    "name": "山土瓜"
  }, {
    "pinyin": "hongjingtian",
    "name": "红景天"
  }, {
    "pinyin": "haozigan",
    "name": "蒿子杆"
  }, {
    "pinyin": "wangwencao",
    "name": "网纹草"
  }, {
    "pinyin": "kuanyeshiwancuo",
    "name": "宽叶十万错"
  }, {
    "pinyin": "longdan",
    "name": "龙胆"
  }, {
    "pinyin": "taoyeshinan",
    "name": "桃叶石楠"
  }, {
    "pinyin": "chiyamaojue",
    "name": "齿牙毛蕨"
  }, {
    "pinyin": "liusushihu",
    "name": "流苏石斛"
  }, {
    "pinyin": "xinghuayulan",
    "name": "星花玉兰"
  }, {
    "pinyin": "sigua",
    "name": "丝瓜"
  }, {
    "pinyin": "liuyeshuigancao",
    "name": "柳叶水甘草"
  }, {
    "pinyin": "lajiao",
    "name": "辣椒"
  }, {
    "pinyin": "lengshan",
    "name": "冷杉"
  }, {
    "pinyin": "guayewutou",
    "name": "瓜叶乌头"
  }, {
    "pinyin": "changganqiuhaitang",
    "name": "昌感秋海棠"
  }, {
    "pinyin": "qie",
    "name": "茄"
  }, {
    "pinyin": "songyejue",
    "name": "松叶蕨"
  }, {
    "pinyin": "hainanzuanhuilan",
    "name": "海南钻喙兰"
  }, {
    "pinyin": "longliye",
    "name": "龙脷叶"
  }, {
    "pinyin": "baihuaxiaosong",
    "name": "白花小松"
  }, {
    "pinyin": "songguoju",
    "name": "松果菊"
  }, {
    "pinyin": "yisuijuanbo",
    "name": "异穗卷柏"
  }, {
    "pinyin": "lanhuameirenjiao",
    "name": "兰花美人蕉"
  }, {
    "pinyin": "qiandaitianjin",
    "name": "千代田锦"
  }, {
    "pinyin": "wendingguo",
    "name": "文定果"
  }, {
    "pinyin": "songhongmei",
    "name": "松红梅"
  }, {
    "pinyin": "liuyuexue",
    "name": "六月雪"
  }, {
    "pinyin": "shenhonglongdan",
    "name": "深红龙胆"
  }, {
    "pinyin": "yuxin",
    "name": "雨心"
  }, {
    "pinyin": "yalezhiwu",
    "name": "雅乐之舞"
  }, {
    "pinyin": "wenmushu",
    "name": "蚊母树"
  }, {
    "pinyin": "mudou",
    "name": "木豆"
  }, {
    "pinyin": "sishumu",
    "name": "四数木"
  }, {
    "pinyin": "caomuxizhuanghuangqi",
    "name": "草木樨状黄耆"
  }, {
    "pinyin": "qihao",
    "name": "奇蒿"
  }, {
    "pinyin": "shisuan",
    "name": "石蒜"
  }, {
    "pinyin": "baiqiu",
    "name": "白楸"
  }, {
    "pinyin": "xiaohongju",
    "name": "小红菊"
  }, {
    "pinyin": "zhangbingyinyeshu",
    "name": "长柄银叶树"
  }, {
    "pinyin": "boluomi",
    "name": "菠萝蜜"
  }, {
    "pinyin": "aizijinniu",
    "name": "矮紫金牛"
  }, {
    "pinyin": "lanlinghua",
    "name": "蓝铃花"
  }, {
    "pinyin": "xiaolanwandailan",
    "name": "小蓝万代兰"
  }, {
    "pinyin": "linhuacao",
    "name": "鳞花草"
  }, {
    "pinyin": "zhimacai",
    "name": "芝麻菜"
  }, {
    "pinyin": "wanxiazhiwu",
    "name": "晚霞之舞"
  }, {
    "pinyin": "kongquezhuyu",
    "name": "孔雀竹芋"
  }, {
    "pinyin": "xihuacao",
    "name": "喜花草"
  }, {
    "pinyin": "zhenyetianlanxiuqiu",
    "name": "针叶天蓝绣球"
  }, {
    "pinyin": "daniuzihua",
    "name": "大纽子花"
  }, {
    "pinyin": "dahualoudoucai",
    "name": "大花耧斗菜"
  }, {
    "pinyin": "tiebaojin",
    "name": "铁包金"
  }, {
    "pinyin": "luoxingcao",
    "name": "罗星草"
  }, {
    "pinyin": "caihongmachixian",
    "name": "彩虹马齿苋"
  }, {
    "pinyin": "boyuanlengshuihua",
    "name": "波缘冷水花"
  }, {
    "pinyin": "xinghuangdoulan",
    "name": "杏黄兜兰"
  }, {
    "pinyin": "putaofengxinzi",
    "name": "葡萄风信子"
  }, {
    "pinyin": "dahejin",
    "name": "大和锦"
  }, {
    "pinyin": "xiongtongzi",
    "name": "熊童子"
  }, {
    "pinyin": "shaolan",
    "name": "杓兰"
  }, {
    "pinyin": "baihuimaodou",
    "name": "白灰毛豆"
  }, {
    "pinyin": "dayedongqing",
    "name": "大叶冬青"
  }, {
    "pinyin": "runnan",
    "name": "润楠"
  }, {
    "pinyin": "huanghualaoyazui",
    "name": "黄花老鸦嘴"
  }, {
    "pinyin": "qinyeshanhu",
    "name": "琴叶珊瑚"
  }, {
    "pinyin": "ersejinguangju",
    "name": "二色金光菊"
  }, {
    "pinyin": "xiamahua",
    "name": "虾蟆花"
  }, {
    "pinyin": "yewandou",
    "name": "野豌豆"
  }, {
    "pinyin": "wabanhua",
    "name": "洼瓣花"
  }, {
    "pinyin": "sheputao",
    "name": "蛇葡萄"
  }, {
    "pinyin": "tiexiancai",
    "name": "铁苋菜"
  }, {
    "pinyin": "qiaocaiguo",
    "name": "壳菜果"
  }, {
    "pinyin": "fujianziwei",
    "name": "福建紫薇"
  }, {
    "pinyin": "niujintiao",
    "name": "牛筋条"
  }, {
    "pinyin": "zhongmianmulian",
    "name": "中缅木莲"
  }

]

Page({

  data: {
    indexList: [],
    flower: []
  },

  onLoad: function(options) {
    wx.showLoading({
      title: '请稍后',
    })

    let temp = flowers;

    //按拼音字母排序
    temp.sort(function(c1,c2){
      return (c1.pinyin.localeCompare(c2.pinyin))
    }) 

    let map = new Map();
    let s = new Set();
    for (let i = 0 ; i < temp.length ; i++){
      let initial = temp[i].pinyin[0].toUpperCase();
      if (initial < 'A' || initial > 'Z'){
        initial = '#';
      }
      if (!s.has(initial)){
        s.add(initial);
        map.set(initial, []);
      }

      map.get(initial).push({name: temp[i].name});
    }

    let keys = [];
    for (let i of map.keys()){
      keys.push(i);
    }
    keys.sort(function(c1, c2){
      if (c1 === '#'){
        return 1;
      }else if (c2 === '#'){
        return -1;
      }else{
        return c1 > c2;
      }
    });

    let list = [];
    for (let i = 0 ; i < keys.length ; i++){
      list.push({
        alpha: keys[i],
        subItems: map.get(keys[i])
      })
    }

    this.setData({
      flower: list,
      indexList: keys
    })

    wx.hideLoading();
  },

  onChoose: function(e){
    let name = e.target.dataset.name;
    let pages = getCurrentPages(); //获取页面栈
    let prevPage = pages[pages.length - 2]; //获取上一页面
    prevPage.setData({
      type: name
    }, () => {
      prevPage.loadPlant();
    })

    wx.navigateBack({
      delta: 1
    })
  }
})